### ISSUE TITLE
Any plan to support old ESP8266 chip? 

### ISSUE THREAD

**Issue by puppywang** [espressif/openocd-esp32#111]
There is an old openocd folk supporting ESP8266, which is based on old openocd v0.9 version, (https://github.com/sysprogs/esp8266-openocd). If we can merge that, it would be easier for enthusiast to debug RTOS on old ESP8266. Thanks.

**Comment by gerekon** [comment]
Hi @puppywang. We are considering the possibility to support ESP8266 in this repo. The support for Xtensa-based chips with different HW options has been improved. See [xtensa.c](https://github.com/espressif/openocd-esp32/blob/master/src/target/xtensa.c) and [xtensa_debug_module.c](https://github.com/espressif/openocd-esp32/blob/master/src/target/xtensa_debug_module.c)
But it is not in our nearest plans and depends on how many people will actually need this.

**Comment by puppywang** [comment]
Got, thanks for your information.

**Comment by erhankur** [comment]
There is no update regarding ESP8266 support. Still waiting in the backlog and needs a priority.
