### ISSUE TITLE
ftdi_layout_signal LED on FT4232HL Board

### ISSUE THREAD

**Issue by BassMatiFreecad** [espressif/openocd-esp32#116]
Release v0.10.0-esp32-20200709

I am working on an FT4232HL board with a JTAG connector attached to channel B. I modifed esp32_devkitj_v1.cfg and got it working with an ESP DevKit v1. However, there are LED signals defined in the config file which I cannot use. I can comment out LED1...3, but must define the LED signal, otherwise I get tons of error messages "LED signal not defined". 

Currently I'm routing the LED to the unused channel B bit 7 (DBGRQ):
ftdi_layout_init 0x0108 0x0b00
ftdi_layout_signal LED -data 0x8000

That seem to work, but I would rather set the value to 0 (i. e. "unused"):
ftdi_layout_signal LED -data 0x0000
Unfortunately this produces the same error message "undefined".

Setting a 32-bit value (which would make sense on FT2232 and FT4232) produces a syntax error:
ftdi_layout_signal LED -data 0x80000000
ftdi_layout_signal LED -data 0x10000
So I cannot use LEDs connected to channels C and D. 

Is that correct?
Can it be changed?

**Comment by igrr** [comment]
Hi @BassMatiFreecad, I see there are some interface config files which do not define the LED signal, like tcl/interface/ftdi/tumpa.cfg. So I think that not defining this signal should work.

Could you please paste the command line your are using to start OpenOCD, and the log output?

**Comment by BassMatiFreecad** [comment]
Console output:

&gt;cd
D:\Progs\esp-idf\openocd-esp32\share\openocd\scripts

&gt;..&bsol;..&bsol;..\bin\openocd -f interface/ftdi/ft4232hl.cfg -f board/esp-wroom-32.cfg
Open On-Chip Debugger  v0.10.0-esp32-20200709 (2020-07-09-08:54)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
adapter speed: 1000 kHz

WARNING: boards/esp-wroom-32.cfg is deprecated, and may be removed in a future release.
Info : Configured 2 cores
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Error: libusb_open() failed with LIBUSB_ERROR_NOT_SUPPORTED
Info : clock speed 1000 kHz
Info : JTAG tap: esp32.cpu0 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : JTAG tap: esp32.cpu1 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : cpu0: Detected debug stubs @ 3ffc0bd4
Info : cpu1: Detected debug stubs @ 3ffc0bd4
Info : Listening on port 3333 for gdb connections
shutdown command invoked
Info : cpu0: Restore debug stubs address 3ffc0bd4
Info : cpu1: Restore debug stubs address 3ffc0bd4
&gt;

So in general it works with my interface config file (see attached file).

[FT4232HL.cfg.txt](https://github.com/espressif/openocd-esp32/files/4995157/FT4232HL.cfg.txt)

If I set the LED value to 0x0000, I get the following output:

&gt;..&bsol;..&bsol;..\\bin\openocd -f interface/ftdi/ft4232hl.cfg -f board/esp-wroom-32.cfg
Open On-Chip Debugger  v0.10.0-esp32-20200709 (2020-07-09-08:54)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
adapter speed: 1000 kHz

WARNING: boards/esp-wroom-32.cfg is deprecated, and may be removed in a future release.
Info : Configured 2 cores
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Error: libusb_open() failed with LIBUSB_ERROR_NOT_SUPPORTED
Info : clock speed 1000 kHz
Error: interface doesn't provide signal 'LED'
... (repeated several times)
Error: interface doesn't provide signal 'LED'
Info : JTAG tap: esp32.cpu0 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : JTAG tap: esp32.cpu1 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Error: interface doesn't provide signal 'LED'
...and so on

If I set 

ftdi_layout_init 0x0008 0x8b0b
ftdi_layout_signal LED -data 0x80000

then I get

&gt;..&bsol;..&bsol;..\bin\openocd -f interface/ftdi/ft4232hl.cfg -f board/esp-wroom-32.cfg
Open On-Chip Debugger  v0.10.0-esp32-20200709 (2020-07-09-08:54)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
data_mask option value ('0x80000') is not valid

It appears to me that with a 16 bit value I can assign the LED to any channel A and B pin. For channels C and D a 32 bit value would be required. Or two 16 bit values as for the fdti_layout_init setting above.

Thanks for your kind reply, it's greatly appreciated!

**Comment by igrr** [comment]
If your adapter doesn't have an LED, then it is sufficient to remove the following line from your config file:
```
ftdi_layout_signal LED -data 0x0000
```
I've tested this locally and there aren't any errors when this option is removed.

Regarding the limitation that signals can only use the lower 16 bits of each channel, it seems that OpenOCD only implements two commands of FTDI MPSSE protocol: mpsse_set_data_bits_low_byte, mpsse_set_data_bits_high_byte. There is probably some way to address the upper 16-bit part of the channel using the MPSSE protocol, but it's not supported in OpenOCD as far as I can tell.

**Comment by BassMatiFreecad** [comment]
>it is sufficient to remove the following line from your config file:

I could swear that I already tried that with no avail - but actually it works! As always, the fault sits in front of the screen... Big thank you!

> some way to address the upper 16-bit part of the channel

The FT4232 is a little bit different from the FT2232, because there are no upper bytes. There are 2 MPSSE on channel 0 and 1 with only the lower 8 data bits broken out to the pins, and two UART/BitBang engines on channels 2 and 3, also 8 bit wide, whereas the FT2232 has only 2 channels with MPSSEs but with 16 bits (8 data and 8 control) each. Both chips seem to have the same pinout.

> but it's not supported in OpenOCD as far as I can tell.

That's what I assumed. Maybe I can look deeper into this matter somewhere in the future.

By the way: The board documentations can be found here: 
    [FT4232HL-Board](https://github.com/arm8686/FT4232HL-Board) and 
    [FT2232HL](https://github.com/arm8686/FT2232HL-Board). 
My project diary:
    https://bassmationcode.gitlab.io/esp32-jtag-debugging-w-ft4232h/index.htm

**Comment by igrr** [comment]
Nice! If you will be looking at VS Code integration, recommend checking out https://github.com/espressif/vscode-esp-idf-extension.
