### ISSUE TITLE
Werror implicit-fallthrough GCC 7.1.1

### ISSUE THREAD

**Issue by KoWu** [espressif/openocd-esp32#13]
With GCC 7.1.1 implicit fallthroughs throw a warning. Because of Werror the build will fail.

If someone else has this issue, as a temporal fix build with:
make -j
wait until the error is thrown and continue with
make -j CFLAGS='-Wno-implicit-fallthrough'

By only using the second make command the build will fail as well with "libusb.h" not found because of some buggy makefile wich does not properly handle CFLAGS???

**Comment by krzychb** [comment]
Thanks, @KoWu!
I have stumbled upon this very issue and your fix made my day :+1:

**Comment by igrr** [comment]
Resolved in 6ac33a8423d24af9579b2022c17163ec97a1ad08.
