### ISSUE TITLE
ESP-PROG dont work (OCD-299)

### ISSUE THREAD

**Issue by iolaso** [espressif/openocd-esp32#140]
Hi.

Im trying to use ESP-PROG to debug on Platform io and the sesult is the next:

Info : tcl server disabled
Info : telnet server disabled
Info : clock speed 5000 kHz
Info : JTAG tap: esp32.cpu0 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : JTAG tap: esp32.cpu1 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : TAP auto0.tap has invalid IDCODE (0x0)
Info : TAP auto1.tap has invalid IDCODE (0x0)
Info : TAP auto2.tap has invalid IDCODE (0x0)
Info : TAP auto3.tap has invalid IDCODE (0x0)
Info : TAP auto4.tap has invalid IDCODE (0x0)
Info : TAP auto5.tap has invalid IDCODE (0x0)
Info : TAP auto6.tap has invalid IDCODE (0x0)
Info : TAP auto7.tap has invalid IDCODE (0x0)
Info : TAP auto8.tap has invalid IDCODE (0x0)
Info : TAP auto9.tap has invalid IDCODE (0x0)
Info : TAP auto10.tap has invalid IDCODE (0x0)
Info : TAP auto11.tap has invalid IDCODE (0x0)
Info : TAP auto12.tap has invalid IDCODE (0x0)
Info : TAP auto13.tap has invalid IDCODE (0x0)
Info : TAP auto14.tap has invalid IDCODE (0x0)
Info : TAP auto15.tap has invalid IDCODE (0x0)
Info : TAP auto16.tap has invalid IDCODE (0x0)
Info : TAP auto17.tap has invalid IDCODE (0x0)
Info : TAP auto18.tap has invalid IDCODE (0x0)
Warn : Unexpected idcode after end of chain: 83 0x00000000
Warn : Unexpected idcode after end of chain: 115 0x00000000
Warn : Unexpected idcode after end of chain: 147 0x00000000
Warn : Unexpected idcode after end of chain: 179 0x00000000
Warn : Unexpected idcode after end of chain: 211 0x00000000
Warn : Unexpected idcode after end of chain: 243 0x00000000
Warn : Unexpected idcode after end of chain: 275 0x00000000
Warn : Unexpected idcode after end of chain: 307 0x00000000
Warn : Unexpected idcode after end of chain: 339 0x00000000
Warn : Unexpected idcode after end of chain: 371 0x00000000
Warn : Unexpected idcode after end of chain: 403 0x00000000
Warn : Unexpected idcode after end of chain: 435 0x00000000
Warn : Unexpected idcode after end of chain: 467 0x00000000
Warn : Unexpected idcode after end of chain: 499 0x00000000
Warn : Unexpected idcode after end of chain: 531 0x00000000
Warn : Unexpected idcode after end of chain: 563 0x00000000
Warn : Unexpected idcode after end of chain: 595 0x00000000
Warn : Unexpected idcode after end of chain: 627 0x00000000
Error: double-check your JTAG setup (interface, speed, ...)
Error: Trying to use configured scan chain anyway...
Warn : AUTO auto0.tap - use "jtag newtap auto0 tap -irlen 2 -expected-id 0x00000000"
Error: auto0.tap: IR capture error; saw 0x0000 not 0x0001
Warn : Bypassing JTAG setup events due to errors
Info : accepting 'gdb' connection from pipe
Warn : No symbols for FreeRTOS!
Error: Target not examined yet
Error executing event gdb-attach on target esp32.cpu0:

Error: Target not halted
Error: auto_probe failed
Error: Connect failed. Consider setting up a gdb-attach event for the target to prepare target for GDB connect, or use 'gdb_memory_map disable'.
Error: attempted 'gdb' connection rejected
Error: error during select: Unknown error
.pioinit:11: Error in sourced command file:
Remote communication error.  Target disconnected.: No error.

Can anyone help me?

**Comment by maxgerhardt** [comment]
Cross-reference to [PlatformIO forum post](https://community.platformio.org/t/esp-prog-debugging-on-a-mac-no-device-found/14658/35?u=maxgerhardt).

**Comment by igrr** [comment]
Hi @iolaso Please also verify that TDI signal connection is correct. Given that OpenOCD is reading some stray zeroes from the scan chain, it looks like TDI is always sampled low. I see two possible situations when this may happen:
* TDI pin is reconfigured in software for some other purpose. The docs on Lyra-T board suggest that it is Aux detect input, please sure that your application is not initializing this pin. Flash a "hello_world" example from ESP-IDF before running OpenOCD, just to be sure.
* There is no connection between ESP-PROG and the development board for this pin. Use a multimeter or a logic analyzer to check that you observe some signals on TDI pin (at the development board side) when OpenOCD starts up.

**Comment by iolaso** [comment]
![image](https://user-images.githubusercontent.com/75091872/106642706-fd9fd480-6588-11eb-8b02-0630a4f017e6.png)
![image](https://user-images.githubusercontent.com/75091872/106642761-10b2a480-6589-11eb-840c-131afdf9cbf0.png)
![1612288933215](https://user-images.githubusercontent.com/75091872/106642903-3e97e900-6589-11eb-8ee7-b274f11b89ab.jpg)
HI!

thanks for the answer, I solder the wires as you can see and the result is te same. By the way I set debug_speed=20.

**Comment by maxgerhardt** [comment]
But now there's no shared GND connection between the programmer and board?

**Comment by iolaso** [comment]
same usb port

**Comment by iolaso** [comment]
but you are right, I forget it

**Comment by iolaso** [comment]
I trying with the blink project from ESP_IDF, it is ok?

**Comment by maxgerhardt** [comment]
Alright in that case it *might* work to share GND.

>I trying with the blink project from ESP_IDF, it is ok?

It should work the same, you can also try and use the [arduino-blink](https://github.com/platformio/platform-espressif32/tree/develop/examples/arduino-blink) instead. 

Have you also checked continuity between the JTAG connections from the ESP-Prog to the IO12 to IO15 pins on the ESP32? Per [schematic](https://dl.espressif.com/dl/schematics/esp32-lyrat-v4.3-schematic.pdf) and labeled pins on the [ESP-WROVER module](https://docs.espressif.com/projects/esp-adf/en/latest/design-guide/board-esp32-lyrat-v4.3.html).

**Comment by iolaso** [comment]
nothing  has changed, same error

**Comment by iolaso** [comment]
> Have you also checked continuity between the JTAG connections from the ESP-Prog to the IO12 to IO15 pins on the ESP32? Per [schematic](https://dl.espressif.com/dl/schematics/esp32-lyrat-v4.3-schematic.pdf) and labeled pins on the [ESP-WROVER module](https://docs.espressif.com/projects/esp-adf/en/latest/design-guide/board-esp32-lyrat-v4.3.html).

Checked, all seems be ok. MTMS IO14, MTCK IO13, MTDO IO15, MTDI IO12.

**Comment by igrr** [comment]
Which signal is the 3rd one on the logic analyzer traces above? It seems to be always low.

**Comment by iolaso** [comment]
> Which signal is the 3rd one on the logic analyzer traces above? It seems to be always low.

Sorry. The order is the next:
1. MTDO
2. MTCK
3. MTDI
4. MTMS

**Comment by igrr** [comment]
Okay, so MTDI is indeed always low, as suggested in https://github.com/espressif/openocd-esp32/issues/140#issuecomment-771196224.

Either some signal on the development board is driving this pin low (Aux detect?), or you got a faulty ESP-PROG board where MTDI is not connected to the FT2232H.

You can distinguish between these possibilities by disconnecting MTDI pin of ESP-PROG from the development board, and attaching the logic analyzer to the MTDI of ESP-PROG. If it is still always low, then ESP-PROG is faulty. If you see that MTDI toggles or is high, then ESP-PROG is fine, but something on the development board is driving the MTDI line low.

**Comment by iolaso** [comment]
ok

**Comment by iolaso** [comment]
I probe it, the EPS-PROG set the MTDI pin to HIGH state by default.

**Comment by igrr** [comment]
Can you try turning DIP switch 7 off? It seems to be connecting Aux detect signal to MTDI.


<img width="921" alt="Screenshot 2021-02-02 at 20 06 16" src="https://user-images.githubusercontent.com/4349050/106649623-24163d80-6592-11eb-984e-452a1be53ef5.png">

**Comment by iolaso** [comment]
ok

**Comment by iolaso** [comment]
Sorry, I had a mistake. The MTDI on the ESP-prog is always off

**Comment by maxgerhardt** [comment]
So it was the DIP switches? Or something on the ESP-prog device? How did you fix it?

**Comment by iolaso** [comment]
I dont fix it

**Comment by iolaso** [comment]
> Okay, so MTDI is indeed always low, as suggested in [#140 (comment)](https://github.com/espressif/openocd-esp32/issues/140#issuecomment-771196224).
> 
> Either some signal on the development board is driving this pin low (Aux detect?), or you got a faulty ESP-PROG board where MTDI is not connected to the FT2232H.
> 
> You can distinguish between these possibilities by disconnecting MTDI pin of ESP-PROG from the development board, and attaching the logic analyzer to the MTDI of ESP-PROG. If it is still always low, then ESP-PROG is faulty. If you see that MTDI toggles or is high, then ESP-PROG is fine, but something on the development board is driving the MTDI line low.

The MTDI pin of the ESP-PROG disconnected for the deleveloment board is low also, so seems like the programmer is faulty.

**Comment by maxgerhardt** [comment]
So you checked per schematics (https://www.espressif.com/sites/default/files/documentation/ESP-Prog_V2.1_reference_design_r1.0.zip) that the ESP-Prog has a fault? Note that there's a buffer between the JTAG header and the actual FTDI chip if you tried to measure a direct connection.

**Comment by iolaso** [comment]
ok, so I check the TDI pin of the ESP-PROG and is in low state, but I dont know what this means. Whats de default state of the TDI pin or how can I check if the ESP-PROG is faulty?

**Comment by iolaso** [comment]
> Can you try turning DIP switch 7 off? It seems to be connecting Aux detect signal to MTDI.
> 
> <img alt="Screenshot 2021-02-02 at 20 06 16" width="921" src="https://user-images.githubusercontent.com/4349050/106649623-24163d80-6592-11eb-984e-452a1be53ef5.png">

Hi, the picture says turn on with JTAG but when, how can I probe that.

**Comment by iolaso** [comment]
> > Can you try turning DIP switch 7 off? It seems to be connecting Aux detect signal to MTDI.
> > <img alt="Screenshot 2021-02-02 at 20 06 16" width="921" src="https://user-images.githubusercontent.com/4349050/106649623-24163d80-6592-11eb-984e-452a1be53ef5.png">
> 
> Hi, the picture says turn on with JTAG but when, how can I probe that.

for JTAG, sorry.

**Comment by iolaso** [comment]
Hi,

I soldered a wire to the pin 17 (MTDI) of the IC to check the status and this is the result.
![image](https://user-images.githubusercontent.com/75091872/106795867-ef21ed80-665a-11eb-92d4-5d4ef8dbe730.png)
![image](https://user-images.githubusercontent.com/75091872/106795940-0365ea80-665b-11eb-8e8c-59fc0669a992.png)
I will buy OPAMP IC to replace.

**Comment by erhankur** [comment]
Closed due to inactivity.

**Comment by mrSilkie** [comment]
I have the same board, same programmer, same problem.

I disconnected AUX and worked straight away. Thank you!
