### ISSUE TITLE
Tensilica On Chip Debugging Guide (OCD-314)

### ISSUE THREAD

**Issue by UweBonnes** [espressif/openocd-esp32#146]
Traces on the web indicate that a document describing  Tesilica On-Chip Debug / onchip_debug_guide.pdf  exists.  However I did not find that document available. I would like to have a look at that document it access implementing  ESP32 debugging in the blackmagic probe.

Can anybody help, with that document or in other ways?

Thanks

**Comment by igrr** [comment]
Greetings @UweBonnes, unfortunately Espressif is unable to distribute the document publicly. However I'm sure we can come up with a solution to give you enough information about the OCD interface. Could you please email me at ivan at company name com?

**Comment by nullptrdesaster** [comment]
may be this from 2010 helps?  https://0x04.net/~mwk/doc/xtensa.pdf

**Comment by UweBonnes** [comment]
Nice document, thaks for the pointer. But not the on-chip debug document I am searching...

**Comment by fariouche** [comment]
Not sure if this document can help
https://www2.lauterbach.com/pdf/debugger_xtensa.pdf

**Comment by UweBonnes** [comment]
This is not the low level JTAG protocol that is needed for reimplementing.
