### ISSUE TITLE
[Bug Report]: EPS32-C3 "Failed to init Debug Adapter" (VSC-727) (OCD-399)

### ISSUE THREAD

**Issue by SilentButeo2** [espressif/openocd-esp32#173]
I try to debug an esp32c3 unit with the integrated serail/jtag functionality over usb.
Building and running with "Build, flash and start monitor on your device" seems to work fine. (using the default hello_world example)
But if I want to debug with F5, I get "Failed to init Debug Adapter".
Don't know if the default launch.json is the correct one for debugging the esp32c3.
I came across several other launch.json files but some of them stated there were out dated.

**HW:**
Using a ESP32-C3-DevKitM-1. Changed it to use the usb serial/jtag functionality.
Running 

**Expected behavior**
Possibility to step through the code

- OS Name & Version :Win10 20H2 (19042.985)
- VSCode Version: 1.59.0
- Python Version: 3.8.7
- ESP-IDF Version: 4.4 (current master build)
- ESP-IDF Extension version 1.1.1

**Logs**
debug.log:
```
2021-08-13 11:16:51,210 - Debug Adapter (main) - CRITICAL - Debug adapter -> Extension: DEBUG_ADAPTER_STARTED
2021-08-13 11:16:51,215 - Debug Adapter (main) - CRITICAL - Debug adapter -> Extension: DEBUG_ADAPTER_READY2CONNECT
2021-08-13 11:16:51,278 - Debug Adapter (main) - CRITICAL - Debug adapter -> Extension: DEBUG_ADAPTER_STOPPED
```

**Settings**
launch.json
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "espidf",
      "name": "Launch",
      "request": "launch"
    }
  ]
}
```

**Comment by nanshanISCK** [comment]
I can start OpenOCD normally and then download binary files using JTAG, but if I press F5 to debug, the following error will be reported
![1713000590299](https://github.com/espressif/openocd-esp32/assets/47286529/dd148a4e-6559-409c-9447-b52a2fc7f1e0)
