### ISSUE TITLE
FTDI DEXT installation : Open OCD fails on MAC OS 11.5.2 (OCD-407)

### ISSUE THREAD

**Issue by rohiniramegowda** [espressif/openocd-esp32#179]
### Environment
- Development Kit: ESP WROVER E
- Module or chip used: ESP WROVER
- Debug Adapter: ESP-PROG
- OpenOCD version: [v0.10.0-esp32-202104012]
- Operating System: MAC OS 11.5.2
- Using an IDE?: NO 
- OpenOCD command line:  openocd -f board/esp32-wrover-kit-3.3v.cfg]
- JTAG Clock: 2000
- ESP-IDF version: 4.2

### Problem Description
Hi ,

I am trying to setup the debugger on ESP WROVER E Kit and I have ESP Prog . I realized that this version of mac does not support kext but dext. I have the beta version downloaded from site and ran it in my application folder . 

I have the port recognized as

cu.usbserial-14220				
cu.usbserial-1423100		
cu.usbserial-1423101

tty.usbserial-14220		
tty.usbserial-1423100		
tty.usbserial-1423101

When I run open OCD I still get the below  error . I am trying this on Command line. Am I missing something ? Is there any documentation I can refer to ?

Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : ftdi: if you experience problems at higher adapter clocks, try the command "ftdi_tdo_sample_edge falling"
Info : clock speed 20000 kHz
Error: JTAG scan chain interrogation failed: all zeroes
Error: Check JTAG interface, timings, target power, etc.
Error: Trying to use configured scan chain anyway...
Error: esp32.cpu0: IR capture error; saw 0x00 not 0x01
Warn : Bypassing JTAG setup events due to errors
Info : Listening on port 3333 for gdb connections

**Comment by erhankur** [comment]
@rohiniramegowda Closing this. If you still have an issue, feel free to re-open.
