### ISSUE TITLE
ESP32 WROVER reboot loop when uploading >4MB via JTAG (OCD-421)

### ISSUE THREAD

**Issue by caiser01** [espressif/openocd-esp32#184]
### Environment
- Development Kit: ESP32-DEVKITC-VE
- Module or chip used: ESP32-WROVER-E (8MB)
- Debug Adapter: ESP-PROG, Segger J-Link
- OpenOCD version: v0.10.0-esp32-20210721
- Operating System: Windows 10, mac OS 10.15.7
- IDE: Visual Studio Code 1.61, PlatformIO Core 5.2.2
- OpenOCD command line: `openocd -f interface/ftdi/esp32_devkitj_v1.cfg -f board/esp-wroom-32.cfg -c "adapter_khz 5000"`
- JTAG Clock: 5000kHz
- ESP-IDF version: v3.3.5-1-g85c43024c

### Problem Description
Code that has been built for the ESP32-WROVER-E (8MB) using an 8MB partition table does not run as expected when uploaded to the DevKit using openocd with a JTAG device such as the ESP-PROG or J-Link.

When uploading code that has been built using an 8MB partition table to the 8MB ESP32 WROVER module using openocd with a JTAG device, the upload process will appear to complete successfully but the ESP32 will go into an infinite reboot loop upon completion. If the same code is uploaded via the DevKit's built-in USB serial port, the code runs normally after the upload completes.

If the code is built using the default 4MB partition table, it can be uploaded using either a JTAG device or the built-in USB port and will run correctly.

1. Create a new ESP32 project in VSCode using PlatformIO with the following files:

main.cpp
```
#include <Arduino.h>

#define LED_BUILTIN 2

void setup() {
    log_d("Total heap: %d", ESP.getHeapSize());
    log_d("Total PSRAM: %d", ESP.getPsramSize());
    log_d("Flash Chip Size: %d", ESP.getFlashChipSize());
    log_d("ESP-IDF version is: %s", ESP.getSdkVersion());

    pinMode(LED_BUILTIN, OUTPUT);
}

void loop() {
    digitalWrite(LED_BUILTIN, HIGH);
    delay(1000);
    digitalWrite(LED_BUILTIN, LOW);
    delay(1000);
}
```
platformio.ini
```
; PlatformIO Project Configuration File

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

; Commenting the line below causes the code to run as expected after uploading via JTAG
board_build.partitions = default_8MB.csv

debug_tool = esp-prog
upload_protocol = esp-prog

build_flags =
    ; Enable PSRAM
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    ; Debug level
    -DCORE_DEBUG_LEVEL=5
    -DESP32=1
```

2. Connect the ESP-PROG (https://docs.espressif.com/projects/espressif-esp-iot-solution/en/latest/hw-reference/ESP-Prog_guide.html) to the JTAG pins of the ESP32 WROVER module (https://docs.espressif.com/projects/esp-idf/en/latest/esp32/_images/esp32-devkitC-v4-pinout.jpg). 
3. Connect the ESP-PROG to the USB port of the PC. Make sure the power LEDs on both the ESP-PROG and ESP32 DevKit are lighted.
4. Build and upload the code.

### Debug Logs
See attached.

[openocd_log_4MB.txt](https://github.com/espressif/openocd-esp32/files/7421125/openocd_log_4MB.txt)
[openocd_log_8MB.txt](https://github.com/espressif/openocd-esp32/files/7421126/openocd_log_8MB.txt)

### Expected behavior
After uploading the code, it should run and produce the following serial output one time regardless of the chosen upload method:
```
rst:0x3 (SW_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5856
entry 0x400806a8
[D][esp32-hal-psram.c:47] psramInit(): PSRAM enabled
[D][main.cpp:6] setup(): Total heap: 387368
[D][main.cpp:7] setup(): Total PSRAM: 4194252
[D][main.cpp:8] setup(): Flash Chip Size: 8388608
[D][main.cpp:9] setup(): ESP-IDF version is: v3.3.5-1-g85c43024c
```

**Comment by caiser01** [comment]
I'm still having this problem so I've attempted to dig a bit deeper.

I now have two test projects in PlatformIO which I'm including in the zip files below so anyone can easily try them:

[esp32blink_Arduino.zip](https://github.com/espressif/openocd-esp32/files/7470571/esp32blink_Arduino.zip)
This program uses only the Arduino-ESP32 framework. When attempting to upload with a JTAG programmer with the 8MB partition table, the ESP32 Wrover continuously crashes and reboots as described in my first post. Uploading the same code over the ESP32 Wrover's USB serial port results in correct operation.

[esp32blink_ESP-IDF.zip](https://github.com/espressif/openocd-esp32/files/7470595/esp32blink_ESP-IDF.zip)
This program uses ESP-IDF framework with Arduino as a component. In this case, when uploading with a JTAG programmer with the 8MB partition table, the Wrover does not crash and the code executes correctly. The partition tables and sdkconfig used here are copied and pasted from arduino-esp32.
https://github.com/espressif/arduino-esp32/blob/master/tools/partitions/default_8MB.csv
https://github.com/espressif/arduino-esp32/blob/master/tools/partitions/default.csv
https://github.com/espressif/arduino-esp32/blob/master/tools/sdk/esp32/sdkconfig

At this point, I don't understand why one project would work over the other.

Does anyone have any ideas?

**Comment by erhankur** [comment]
Hi @caiser01,

When I look at to the PIO pre-built bootloader files in the `.platformio/packages/framework-arduinoespressif32/tools/sdk/bin/` directory, all of them are configured for the 4MB flash. 

I am not familiar with the PIO internals to suggest you the right settings but if you replace `bootloader_dio_40m.bin` with the attached one, you should be able to upload and run your program via `esp-prog`

This bootloader built by idf 3.3.5

[bootloader_dio_40m.bin.zip](https://github.com/espressif/openocd-esp32/files/7664874/bootloader_dio_40m.bin.zip)

**Comment by caiser01** [comment]
@erhankur,

Thanks for the insight and bootloader file. I substituted your version of the bootloader in the Arduino version of the project and the code then executed correctly after being flashed with the ESP-PROG.
```
ets Jul 29 2019 12:21:46

rst:0x3 (SW_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:6704
ho 0 tail 12 room 4
load:0x40078000,len:12152
ho 0 tail 12 room 4
load:0x40080400,len:6664
entry 0x40080774
I (75) boot: Chip Revision: 3
I (75) boot_comm: chip revision: 3, min. bootloader chip revision: 0
I (43) boot: ESP-IDF v3.3.5 2nd stage bootloader
I (43) boot: compile time 22:37:58
I (43) boot: Enabling RNG early entropy source...
I (48) boot: SPI Speed      : 40MHz
I (52) boot: SPI Mode       : DIO
I (56) boot: SPI Flash Size : 8MB
I (60) boot: Partition Table:
I (64) boot: ## Label            Usage          Type ST Offset   Length
I (71) boot:  0 nvs              WiFi data        01 02 00009000 00005000
I (78) boot:  1 otadata          OTA data         01 00 0000e000 00002000
I (86) boot:  2 app0             OTA app          00 10 00010000 00330000
I (93) boot:  3 app1             OTA app          00 11 00340000 00330000
I (101) boot:  4 spiffs           Unknown data     01 82 00670000 00190000
I (108) boot: End of partition table
I (113) boot_comm: chip revision: 3, min. application chip revision: 0
I (120) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x14dac ( 85420) map
I (159) esp_image: segment 1: paddr=0x00024dd4 vaddr=0x3ffbdb60 size=0x0235c (  9052) load
I (163) esp_image: segment 2: paddr=0x00027138 vaddr=0x40080000 size=0x08ed8 ( 36568) load
I (181) esp_image: segment 3: paddr=0x00030018 vaddr=0x400d0018 size=0x1badc (113372) map
I (221) esp_image: segment 4: paddr=0x0004bafc vaddr=0x40088ed8 size=0x05cb8 ( 23736) load
I (240) boot: Loaded app from partition at offset 0x10000
I (240) boot: Disabling RNG early entropy source...
[D][esp32-hal-psram.c:47] psramInit(): PSRAM enabled
[D][main.cpp:6] setup(): Total heap: 387396
[D][main.cpp:7] setup(): Total PSRAM: 4194252
[D][main.cpp:8] setup(): Flash Chip Size: 8388608
[D][main.cpp:9] setup(): ESP-IDF version is: v3.3.5-1-g85c43024c
```
Am I correct that you just re-compiled the bootloader with 8MB flash and verbose output enabled?

Re-compiling the bootloader may be a viable workaround in my case but perhaps not for less experienced users.

If the pre-built bootloaders for the Arduino framework are all configured for 4MB of flash, I'm wondering why they work with an 8MB partition table when you upload via USB serial port but not when uploading via ESP-PROG or other JTAG programmer?

**Comment by caiser01** [comment]
@erhankur,

Ah, I see! I did not know that esptool was changing the bootloader on the fly. That explains everything.

I will do as you suggest and create a feature request for 8MB and 16MB flash support over at https://github.com/platformio/platform-espressif32

Thanks again!

**Comment by caiser01** [comment]
I've converted the issue I originally filed at platform-espressif32 into a feature request: https://github.com/platformio/platform-espressif32/issues/648

I've also updated my community post on this subject at PlatformIO: https://community.platformio.org/t/esp32-reboot-loop-when-uploading-4mb-via-jtag/24048
