### ISSUE TITLE
ESP32-S3: Debugging only works every other try (OCD-422)

### ISSUE THREAD

**Issue by felixandra** [espressif/openocd-esp32#185]
## Environment

- Development Kit: ESP32-S3-DevKitC-1
- Kit version: v1.0
- Module or chip used: ESP32-­S3­-WROOM­-1
- IDF version: v4.4-dev-3401-gb86fe0c66c
- Build System: idf.py
- Compiler version (Ran ``xtensa-esp32s3-elf-gcc --version``): xtensa-esp32s3-elf-gcc.exe (crosstool-NG esp-2021r1) 8.4.0
- Operating System: Windows
- (Windows only) environment type: PowerShell
- Using an IDE?: Yes, Eclipse (Version: 2021-06 (4.20.0))
- Power Supply: USB

## Problem Description

Debugging on the ESP32-S3-DevKitC-1 only works every other try.

### Expected Behavior

Eclipse debugging should start without error message and stop at the app_main breakpoint.

Powershell (OpenOCD):

```
Info : accepting 'gdb' connection on tcp/3333
Info : New GDB Connection: 1, Target esp32s3.cpu0, state: halted
Info : JTAG tap: esp32s3.cpu0 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : JTAG tap: esp32s3.cpu1 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : esp32s3.cpu0: Debug controller was reset.
Info : esp32s3.cpu0: Core was reset.
Info : esp32s3.cpu0: Target halted, PC=0x500000E7, debug_reason=00000000
Info : esp32s3.cpu0: Core was reset.
Info : esp32s3.cpu0: Target halted, PC=0x40000400, debug_reason=00000000
Info : esp32s3.cpu1: Debug controller was reset.
Info : esp32s3.cpu1: Core was reset.
Info : esp32s3.cpu1: Target halted, PC=0x40000400, debug_reason=00000000
Info : esp32s3.cpu0: Target halted, PC=0x42004E28, debug_reason=00000001
Info : Set GDB target to 'esp32s3.cpu0'
Info : esp32s3.cpu1: Debug controller was reset.
Info : esp32s3.cpu1: Core was reset.
Info : esp32s3.cpu1: Target halted, PC=0x42019FD6, debug_reason=00000000
```

(This is how it looks when it works, which it does every other debug session in Eclipse)

### Actual Behavior

(This is what it looks like the rest of the time, when debugging fails)

Error message in Eclipse:

```
Error in final launch sequence:

Failed to execute MI command:
-exec-continue

Error message from debugger back end:
The program is not being run.
Failed to execute MI command:
-exec-continue

Error message from debugger back end:
The program is not being run.
The program is not being run.
```

Powershell (OpenOCD):

```
Info : accepting 'gdb' connection on tcp/3333
Info : New GDB Connection: 1, Target esp32s3.cpu0, state: halted
Info : JTAG tap: esp32s3.cpu0 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : JTAG tap: esp32s3.cpu1 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : esp32s3.cpu0: Debug controller was reset.
Info : esp32s3.cpu0: Core was reset.
Info : esp32s3.cpu0: Target halted, PC=0x500000E7, debug_reason=00000000
Info : esp32s3.cpu0: Core was reset.
Info : esp32s3.cpu0: Target halted, PC=0x40000400, debug_reason=00000000
Info : esp32s3.cpu1: Debug controller was reset.
Info : esp32s3.cpu1: Core was reset.
Info : esp32s3.cpu1: Target halted, PC=0x40000400, debug_reason=00000000
Info : dropped 'gdb' connection
```

### Steps to reproduce

1. In Powershell: `openocd -f board/esp32s3-builtin.cfg`.
2. In Eclipse: Start debugging.

### Debug configuration (in Eclipse)

**Debugger**
- GDB Setup
  - GDB Command: `xtensa-esp32s3-elf-gdb`
- Remote Target
  - [x] Use remote target
  - [ ] Remote timeout
  - JTAG Device: `OpenOCD (via socket)`
  - GDB Connection String: `localhost:3333`
- [ ] Force thread list update on suspend

**Startup**
- Initialization Commands
  - [ ] Reset and Delay
  - [ ] Halt
  ```
  mon reset halt
  flushregs
  set remote hardware-watchpoint-limit 2
  ```
- Load Image and Symbols
  - [ ] Load image
  - [x] Load symbols
- Run Commands
  - [ ] Set program counter at (hex):
  - [x] Set breakpoint at: `app_main`
  - [x] Resume

**Comment by kolipakakondal** [comment]
Hi @gerekon Based on the log would you suggest anything I could investigate further in the eclipse ide settings or is it specific to OpenOCD and board?


```
Debug: 1368 43223 gdb_server.c:3358 gdb_input_inner(): received packet: 'Hg0'
Debug: 1369 43223 rtos.c:434 rtos_thread_packet(): RTOS: GDB requested to set current thread to 0x0
Debug: 1370 43223 gdb_server.c:402 gdb_put_packet_inner(): sending packet '$OK#9a'
Debug: 1371 43254 gdb_server.c:1043 gdb_connection_closed(): GDB Close, Target: esp32s3.cpu0, state: halted, gdb_actual_connections=0
Debug: 1372 43254 target.c:1638 target_call_event_callbacks(): target event 6 (gdb-end) for core esp32s3.cpu0
Debug: 1373 43254 esp32s3.c:569 esp32s3_handle_target_event(): 6
Debug: 1374 43254 esp_xtensa_smp.c:600 esp_xtensa_smp_handle_target_event(): 6
Debug: 1375 43254 esp_xtensa.c:110 esp_xtensa_handle_target_event(): 6
Debug: 1376 43254 xtensa.c:2447 xtensa_handle_target_event(): 6
Debug: 1377 43254 target.c:1638 target_call_event_callbacks(): target event 20 (gdb-detach) for core esp32s3.cpu0
Debug: 1378 43254 esp32s3.c:569 esp32s3_handle_target_event(): 20
Debug: 1379 43254 esp_xtensa_smp.c:600 esp_xtensa_smp_handle_target_event(): 20
Debug: 1380 43254 esp_xtensa.c:110 esp_xtensa_handle_target_event(): 20
Debug: 1381 43254 xtensa.c:2447 xtensa_handle_target_event(): 20
Info : 1382 43254 server.c:577 server_loop(): dropped 'gdb' connection
```

**Comment by gerekon** [comment]
@felixandra 
Looks like GDB accidentally closes connection. Probably because it crashes.

I set up Eclipse environment with IDF Eclipse plugin on my Windows virtual machine and tested multiple debugging sessions with blink example. I used both options: relaunch debug button and pressing terminate debug button followed by clean debug start. I had no any problems.

I used the following environment:
- Eclipse (Version: 2021-06 (4.20.0))
- The latest IDF v4.4rc1 installed with ESP-IDF Tools Installer for Windows
- OpenOCD v0.11.0-esp32-20211220. It is default for that IDF version.

**Comment by MPC-BlackBox** [comment]
I have this problem debugging ESP32-S2 device. My eclipse setup worked okay until I did the latest upgrade.
Now I have to have two tries to start the debugger.
I have tried checking the debug logs but I cannot see anything obvious.
OpenOCD - v0.10.0-esp32-20210401
ESP-IDF v4.3.1
Espressif IDF Plugins for Eclipse	2.4.0.202201280731

**Comment by MPC-BlackBox** [comment]
I have updated my system to the latest releases but I still have the issue where the debugger only works every other try
OpenOCD - v0.11.0-esp32-20211220
ESP-IDF ESP-IDF v4.4-dirty
Espressif IDF Plugins for Eclipse 2.4.0.202201280731
```
* xtensa-esp32-elf: Toolchain for Xtensa (ESP32) based on GCC
  - esp-2021r2-8.4.0 (recommended, installed)
* xtensa-esp32s2-elf: Toolchain for Xtensa (ESP32-S2) based on GCC
  - esp-2021r2-8.4.0 (recommended, installed)
* xtensa-esp32s3-elf: Toolchain for Xtensa (ESP32-S3) based on GCC
  - esp-2021r2-8.4.0 (recommended, installed)
* xtensa-clang: LLVM for Xtensa (ESP32, ESP32-S2) based on clang (optional)
  - 12.0.1-d9341b81fc (recommended, installed)
* riscv32-esp-elf: Toolchain for 32-bit RISC-V based on GCC
  - esp-2021r2-8.4.0 (recommended, installed)
* esp32ulp-elf: Toolchain for ESP32 ULP coprocessor
  - 2.28.51-esp-20191205 (recommended, installed)
* esp32s2ulp-elf: Toolchain for ESP32-S2 and ESP32-S3 ULP coprocessors
  - 2.28.51-esp-20191205 (recommended, installed)
* cmake: CMake build system (optional)
  - 3.20.3 (recommended, installed)
* openocd-esp32: OpenOCD for ESP32
  - v0.11.0-esp32-20211220 (recommended, installed)
* ninja: Ninja build system (optional)
  - 1.10.2 (recommended, installed)
```

**Comment by MPC-BlackBox** [comment]
I have attached an OpenOCD log for a working connection then the failed connection
[oocd.log](https://github.com/espressif/openocd-esp32/files/7972158/oocd.log)
.

**Comment by QGB** [comment]
```
Type "apropos -v word" for full documentation of commands related to "word".                                            Command name abbreviations are allowed if unambiguous.                                                                  (gdb) c                                                                                                                 The program is not being run. 

(gdb) mon reset halt                                                                                                    "monitor" command not supported by this target.   
```

**Comment by erhankur** [comment]
@MPC-BlackBox Please try the latest OpenOCD and Eclipse plugins. Let us know if you still have an issue.
