### ISSUE TITLE
GDB debugger backend error in Eclipse (OCD-423)

### ISSUE THREAD

**Issue by TomSack** [espressif/openocd-esp32#186]
### Environment
- Module or chip used: ESP32-WROVER
- Debug Adapter: ESP-PROG
- OpenOCD version: v0.10.0-esp32-20200902
- Operating System: Windows10
- Using an IDE: Eclipse 2021-06
- OpenOCD command line: openocd -f board/esp32-wrover-kit-3.3v.cfg
- JTAG Clock: default
- ESP-IDF version: v4.3

### Problem Description
1. start openocd in Windows cmd window: openocd -f board/esp32-wrover-kit-3.3v.cfg
2. Start gdb debug session in  Eclipse
3. Eclipse debug configuration is set up according to https://docs.espressif.com/projects/esp-idf/en/v4.3/esp32/api-guides/jtag-debugging/debugging-examples.html#jtag-debugging-examples-eclipse
4. Eclipse error: Error in final launch sequence.

### Debug Logs
[openocd_log.txt](https://github.com/espressif/openocd-esp32/files/7426969/openocd_log.txt)

### Expected behavior
GDB bugging starting with break point at app_main.

### Screenshots
![Eclipse error msg](https://user-images.githubusercontent.com/56383922/139086150-73d1aae3-a80e-404d-92d5-cd863068f2d9.PNG)

**Comment by erhankur** [comment]
Closed due to inactivity.
