### ISSUE TITLE
Build Bootstrap AC_INIT Error (OCD-424)

### ISSUE THREAD

**Issue by vindicatorr** [espressif/openocd-esp32#187]
### Environment
- OpenOCD version: [Master]
- Operating System: [Linux]

### Problem Description
1. ./en/esp32c3/html/api-guides/jtag-debugging/building-openocd-linux.html
2. `$ git clone --recursive https://github.com/espressif/openocd-esp32.git`
3. `$ cd openocd-esp32`
4. `$ ./bootstrap`

### Debug Logs
Attach verbose debug logs for OpenOCD and GDB.  See [item 3 here](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/jtag-debugging/tips-and-quirks.html#reporting-issues-with-openocd-gdb) for how to generate verbose logs.
```
+ aclocal
configure.ac:16: error: AC_INIT should be called with package and version arguments
/usr/share/aclocal-1.16/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
configure.ac:16: the top level
autom4te: error: /usr/bin/m4 failed with exit status: 1
aclocal: error: autom4te failed with exit status: 1
```

### Expected behavior
Bootstrap should succeed, allow `configure` file to be generated.

### Other
Changing `configure.ac` `AC_INIT([openocd], [ ],` to `AC_INIT([openocd], [1.0],` allows this issue to pass.

EDIT0:
To add to this issue relating to the documentation for building this openocd, build still fails with warnings being treated as errors.
Adding the `--disable-werror` parameter to `configure`, allows the build to continue and finish:
```
$ ./src/openocd --version
Open On-Chip Debugger 1.078ea2222-dirty (2021-10-28-09:25)
```

**Comment by meltdown03** [comment]
If you change line 2 of `configure.ac` from `AC_INIT([openocd], [  ]` to `AC_INIT([openocd], [ "" ]` (add the quotes where the version would go) it works also and keeps the version correct except the `-dirty` is still there

**Comment by TravisRo** [comment]
This is still an issue when using MSYS2 MinGW 64 x86 on windows. Since it's such a simple one line fix, a patch would be appreciated.  I install msys2 mingw64 using the guide provided by espressif here:
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/jtag-debugging/building-openocd-windows.html

**Comment by erhankur** [comment]
This issue should have been fixed in https://github.com/espressif/openocd-esp32/commit/54aff94f1a50f409c7188a1e21a0349a8a69c356 

Can you please check?

**Comment by erhankur** [comment]
Solution provided. Closed.
