### ISSUE TITLE
Trouble building from sources (OCD-551)

### ISSUE THREAD

**Issue by brentonjudge** [espressif/openocd-esp32#227]
### Development Kit

ESP32-C3

### Module or chip used

ESP32-C3-WROOM-02

### Debug Adapter

UART

### OpenOCD version

20220411

### Operating System

Windows

### Using an IDE ?

No

### OpenOCD command line

N/A

### JTAG Clock Speed

n/A

### ESP-IDF version

N/A

### Problem Description

When attempting to build under MingW32 am getting an error with jimtcl 

make  all-recursive
make[1]: Entering directory '/home/brenton/esp/openocd-esp32'
Making all in jimtcl
make[2]: Entering directory '/home/brenton/esp/openocd-esp32/jimtcl'
make[2]: *** No rule to make target 'all'.  Stop.
make[2]: Leaving directory '/home/brenton/esp/openocd-esp32/jimtcl'
make[1]: *** [Makefile:5157: all-recursive] Error 1
make[1]: Leaving directory '/home/brenton/esp/openocd-esp32'
make: *** [Makefile:2092: all] Error 2
 

### Expected behavior

Should compile

**Comment by gerekon** [comment]
Hi,

Did you do the following steps before building?
1) `git submodule update --init --recursive`
2) `./bootstrap`
3) `configure <any opts>`

What MinGW distribution do you use? What shell do you use for building: msys, cmd, powershell?

**Comment by brentonjudge** [comment]
Thanks for the response.

1-3 yes. following instructions and options from https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/api-guides/jtag-debugging/building-openocd-windows.html (pasting all parts), so configure was
./configure --disable-doxygen-pdf --enable-ftdi --enable-jlink --enable-ulink --build=i686-w64-mingw32 --host=i686-w64-mingw32

msys2-x86_64-20220503 and using mingw32 shell.

$ ./configure --disable-doxygen-pdf --enable-ftdi --enable-jlink --enable-ulink --build=i686-w64-mingw32 --host=i686-w64-mingw32
configure: loading site script /etc/config.site
checking for makeinfo... no
configure: WARNING: Info documentation will not be built.
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for i686-w64-mingw32-gcc... i686-w64-mingw32-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether i686-w64-mingw32-gcc accepts -g... yes
checking for i686-w64-mingw32-gcc option to enable C11 features... none needed
checking whether i686-w64-mingw32-gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of i686-w64-mingw32-gcc... gcc3
checking for i686-w64-mingw32-ranlib... no
checking for ranlib... ranlib
checking for i686-w64-mingw32-pkg-config... /mingw32/bin/i686-w64-mingw32-pkg-config
checking pkg-config is at least version 0.23... yes
checking build system type... i686-w64-mingw32
checking host system type... i686-w64-mingw32
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by i686-w64-mingw32-gcc... C:/msys64/mingw32/i686-w64-mingw32/bin/ld.exe
checking if the linker (C:/msys64/mingw32/i686-w64-mingw32/bin/ld.exe) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /mingw32/bin/nm -B
checking the name lister (/mingw32/bin/nm -B) interface... BSD nm
checking whether ln -s works... no, using cp -pR
checking the maximum length of command line arguments... 8192
checking how to convert i686-w64-mingw32 file names to i686-w64-mingw32 format... func_convert_file_msys_to_w32
checking how to convert i686-w64-mingw32 file names to toolchain format... func_convert_file_msys_to_w32
checking for C:/msys64/mingw32/i686-w64-mingw32/bin/ld.exe option to reload object files... -r
checking for i686-w64-mingw32-objdump... no
checking for objdump... objdump
checking how to recognize dependent libraries... file_magic ^x86 archive import|^x86 DLL
checking for i686-w64-mingw32-dlltool... no
checking for dlltool... dlltool
checking how to associate runtime and link libraries... func_cygming_dll_for_implib
checking for i686-w64-mingw32-ar... no
checking for ar... ar
checking for archiver @FILE support... @
checking for i686-w64-mingw32-strip... no
checking for strip... strip
checking for i686-w64-mingw32-ranlib... ranlib
checking command to parse /mingw32/bin/nm -B output from i686-w64-mingw32-gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for i686-w64-mingw32-mt... no
checking for mt... no
checking if : is a manifest tool... no
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for dlfcn.h... no
checking for objdir... .libs
checking if i686-w64-mingw32-gcc supports -fno-rtti -fno-exceptions... no
checking for i686-w64-mingw32-gcc option to produce PIC... -DDLL_EXPORT -DPIC
checking if i686-w64-mingw32-gcc PIC flag -DDLL_EXPORT -DPIC works... yes
checking if i686-w64-mingw32-gcc static flag -static works... yes
checking if i686-w64-mingw32-gcc supports -c -o file.o... yes
checking if i686-w64-mingw32-gcc supports -c -o file.o... (cached) yes
checking whether the i686-w64-mingw32-gcc linker (C:/msys64/mingw32/i686-w64-mingw32/bin/ld.exe) supports shared libraries... yes
checking dynamic linker characteristics... Win32 ld.exe
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking for an ANSI C-conforming const... yes
checking for unsigned long long int... yes
checking for long long int... yes
checking for library containing ioperm... no
checking for library containing dlopen... no
checking for library containing openpty... no
checking for library containing deflate... -lz
checking for sys/socket.h... no
checking for elf.h... no
checking how to run the C preprocessor... i686-w64-mingw32-gcc -E
checking for dirent.h... yes
checking for fcntl.h... yes
checking for malloc.h... yes
checking for netdb.h... no
checking for poll.h... no
checking for pthread.h... yes
checking for zlib.h... yes
checking for strings.h... (cached) yes
checking for sys/ioctl.h... no
checking for sys/param.h... yes
checking for sys/select.h... no
checking for sys/stat.h... (cached) yes
checking for sys/sysctl.h... no
checking for sys/time.h... yes
checking for sys/types.h... (cached) yes
checking for unistd.h... (cached) yes
checking for arpa/inet.h... no
checking for ifaddrs.h... no
checking for netinet/in.h... no
checking for netinet/tcp.h... no
checking for net/if.h... no
checking whether to enable assertions... yes
checking for _Bool... yes
checking for stdbool.h that conforms to C99... yes
checking whether byte ordering is bigendian... no
checking for strndup... no
checking for strnlen... yes
checking for gettimeofday... yes
checking for usleep... yes
checking for vasprintf... yes
checking for realpath... no
checking whether to build a release... no
checking whether to build Doxygen as HTML... yes
checking whether to build Doxygen as PDF... no
checking whether to enable verbose USB I/O messages... no
checking whether to enable verbose USB communication messages... no
checking whether to enable malloc free space logging... no
checking for libusb-1.0... yes
configure: libusb-1.0 header bug workaround: LIBUSB1_CFLAGS changed to "-isystem C:/msys64/home/brenton/libusb/libusb-1.0.21/dist/include/libusb-1.0"
checking for capstone... no
checking for hidapi... no
checking for hidapi-hidraw... no
checking for hidapi-libusb... no
checking for libftdi1... no
checking for libftdi... no
checking for libgpiod... no
checking for libjaylink >= 0.2... no
checking for environ in unistd.h and stdlib.h... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
=== configuring in jimtcl (/home/brenton/esp/openocd-esp32/jimtcl)
configure: running /bin/sh ./configure.gnu --disable-option-checking '--prefix=/mingw32'  '--disable-doxygen-pdf' '--enable-ftdi' '--enable-jlink' '--enable-ulink' '--build=i686-w64-mingw32' '--host=i686-w64-mingw32' 'build_alias=i686-w64-mingw32' 'host_alias=i686-w64-mingw32' 'CFLAGS= -Wno-error -Wno-error' 'LDFLAGS= -L/home/brenton/esp/libusb/MinGW32/.libs/dll' 'CPPFLAGS= -D__USE_MINGW_ANSI_STDIO=1 -Wno-error -I/home/brenton/esp/libusb/include/libusb-1.0 -D__USE_MINGW_ANSI_STDIO=1 -Wno-error' 'PKG_CONFIG_PATH=/home/brenton/libusb/libusb-1.0.21/dist/lib/pkgconfig' --cache-file=/dev/null --srcdir=.
configure: loading site script /etc/config.site
configure: creating ./config.status
=== configuring in src/jtag/drivers/libjaylink (/home/brenton/esp/openocd-esp32/src/jtag/drivers/libjaylink)
configure: running /bin/sh ./configure.gnu --disable-option-checking '--prefix=/mingw32'  '--disable-doxygen-pdf' '--enable-ftdi' '--enable-jlink' '--enable-ulink' '--build=i686-w64-mingw32' '--host=i686-w64-mingw32' 'build_alias=i686-w64-mingw32' 'host_alias=i686-w64-mingw32' 'CFLAGS= -Wno-error -Wno-error' 'LDFLAGS= -L/home/brenton/esp/libusb/MinGW32/.libs/dll' 'CPPFLAGS= -D__USE_MINGW_ANSI_STDIO=1 -Wno-error -I/home/brenton/esp/libusb/include/libusb-1.0 -D__USE_MINGW_ANSI_STDIO=1 -Wno-error' 'PKG_CONFIG_PATH=/home/brenton/libusb/libusb-1.0.21/dist/lib/pkgconfig' --cache-file=/dev/null --srcdir=.
configure: loading site script /etc/config.site
checking build system type... i686-w64-mingw32
checking host system type... i686-w64-mingw32
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for i686-w64-mingw32-gcc... i686-w64-mingw32-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether i686-w64-mingw32-gcc accepts -g... yes
checking for i686-w64-mingw32-gcc option to enable C11 features... none needed
checking whether i686-w64-mingw32-gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of i686-w64-mingw32-gcc... gcc3
checking for i686-w64-mingw32-ar... no
checking for i686-w64-mingw32-lib... no
checking for i686-w64-mingw32-link... no
checking for ar... ar
checking the archiver (ar) interface... ar
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by i686-w64-mingw32-gcc... C:/msys64/mingw32/i686-w64-mingw32/bin/ld.exe
checking if the linker (C:/msys64/mingw32/i686-w64-mingw32/bin/ld.exe) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /mingw32/bin/nm -B
checking the name lister (/mingw32/bin/nm -B) interface... BSD nm
checking whether ln -s works... no, using cp -pR
checking the maximum length of command line arguments... 8192
checking how to convert i686-w64-mingw32 file names to i686-w64-mingw32 format... func_convert_file_msys_to_w32
checking how to convert i686-w64-mingw32 file names to toolchain format... func_convert_file_msys_to_w32
checking for C:/msys64/mingw32/i686-w64-mingw32/bin/ld.exe option to reload object files... -r
checking for i686-w64-mingw32-objdump... no
checking for objdump... objdump
checking how to recognize dependent libraries... file_magic ^x86 archive import|^x86 DLL
checking for i686-w64-mingw32-dlltool... no
checking for dlltool... dlltool
checking how to associate runtime and link libraries... func_cygming_dll_for_implib
checking for i686-w64-mingw32-ar... ar
checking for archiver @FILE support... @
checking for i686-w64-mingw32-strip... no
checking for strip... strip
checking for i686-w64-mingw32-ranlib... no
checking for ranlib... ranlib
checking command to parse /mingw32/bin/nm -B output from i686-w64-mingw32-gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for i686-w64-mingw32-mt... no
checking for mt... no
checking if : is a manifest tool... no
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for dlfcn.h... no
checking for objdir... .libs
checking if i686-w64-mingw32-gcc supports -fno-rtti -fno-exceptions... no
checking for i686-w64-mingw32-gcc option to produce PIC... -DDLL_EXPORT -DPIC
checking if i686-w64-mingw32-gcc PIC flag -DDLL_EXPORT -DPIC works... yes
checking if i686-w64-mingw32-gcc static flag -static works... yes
checking if i686-w64-mingw32-gcc supports -c -o file.o... yes
checking if i686-w64-mingw32-gcc supports -c -o file.o... (cached) yes
checking whether the i686-w64-mingw32-gcc linker (C:/msys64/mingw32/i686-w64-mingw32/bin/ld.exe) supports shared libraries... yes
checking whether -lc should be explicitly linked in... yes
checking dynamic linker characteristics... Win32 ld.exe
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for i686-w64-mingw32-pkg-config... /mingw32/bin/i686-w64-mingw32-pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for libusb-1.0 >= 1.0.16... yes
checking whether byte ordering is bigendian... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating libjaylink/Makefile
config.status: creating libjaylink/version.h
config.status: creating libjaylink.pc
config.status: creating Doxyfile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands

libjaylink configuration summary:
 - Package version ................ 0.2.0-git-f73ad5e
 - Library version ................ 0:0:0
 - Installation prefix ............ /mingw32
 - Building on .................... i686-w64-mingw32
 - Building for ................... i686-w64-mingw32

Enabled transports:
 - USB ............................ yes
 - TCP ............................ yes



OpenOCD configuration summary
--------------------------------------------------
MPSSE mode of FTDI based devices        yes
ST-Link Programmer                      yes (auto)
TI ICDI JTAG Programmer                 yes (auto)
Keil ULINK JTAG Programmer              yes
Altera USB-Blaster II Compatible        yes (auto)
Bitbang mode of FT232R based devices    yes (auto)
Versaloon-Link JTAG Programmer          yes (auto)
TI XDS110 Debug Probe                   yes (auto)
CMSIS-DAP v2 Compliant Debugger         yes (auto)
OSBDM (JTAG only) Programmer            yes (auto)
eStick/opendous JTAG Programmer         yes (auto)
Olimex ARM-JTAG-EW Programmer           yes (auto)
Raisonance RLink JTAG Programmer        yes (auto)
USBProg JTAG Programmer                 yes (auto)
Andes JTAG Programmer                   yes (auto)
Espressif JTAG Programmer               yes (auto)
CMSIS-DAP Compliant Debugger            no
Nu-Link Programmer                      no
Cypress KitProg Programmer              no
Altera USB-Blaster Compatible           no
ASIX Presto Adapter                     no
OpenJTAG Adapter                        no
Linux GPIO bitbang through libgpiod     no
SEGGER J-Link Programmer                yes
Bus Pirate                              no
Use Capstone disassembly framework      no

**Comment by brentonjudge** [comment]
Hi, external downloaded the jimtcl libraries and then copied them over seems to have resolved the issue.  Not sure what the difference was but it resolved the problem.  Unfortunately it didn't resolve the issue in programming the ESP32C3 chips.

**Comment by gerekon** [comment]
Нуыб Ш сруслув нщг сщYes, I checked your config and build went successful. Looks like you had problems with updating `jimtcl` submodule.
