### ISSUE TITLE
starting and running debugger on esp32s3 esp32-s3-devkitc-1 (OCD-560)

### ISSUE THREAD

**Issue by suskach** [espressif/openocd-esp32#229]
### Development Kit

esp32-s3-devkitc-1

### Module or chip used

esp32-s3-devkitc-1

### Debug Adapter

gdb and openocd

### OpenOCD version

Open On-Chip Debugger  v0.11.0-esp32-20211220 (2021-12-20-15:43)

### Operating System

windows 10

### Using an IDE ?

Eclipse

### OpenOCD command line

openocd -f board/esp32s3-builtin.cfg

### JTAG Clock Speed

na

### ESP-IDF version

4.4.1

### Problem Description

:\Users\suskach\workspace\blink>openocd -f board/esp32s3-builtin.cfg
Open On-Chip Debugger  v0.11.0-esp32-20211220 (2021-12-20-15:43)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Info : only one transport option; autoselect 'jtag'
Info : esp_usb_jtag: VID set to 0x303a and PID to 0x1001
Info : esp_usb_jtag: capabilities descriptor set to 0x2000
Warn : Transport "jtag" was already selected
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Error: esp_usb_jtag: could not find or open device!

Assertion failed!

Program: C:\Espressif\tools\openocd-esp32\v0.11.0-esp32-20211220\openocd-esp32\bin\openocd.exe
File: ../src/jtag/core.c, Line 343

### Debug Logs

```shell
:\Users\suskach\workspace\blink>openocd -f board/esp32s3-builtin.cfg
Open On-Chip Debugger  v0.11.0-esp32-20211220 (2021-12-20-15:43)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Info : only one transport option; autoselect 'jtag'
Info : esp_usb_jtag: VID set to 0x303a and PID to 0x1001
Info : esp_usb_jtag: capabilities descriptor set to 0x2000
Warn : Transport "jtag" was already selected
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Error: esp_usb_jtag: could not find or open device!

Assertion failed!

Program: C:\Espressif\tools\openocd-esp32\v0.11.0-esp32-20211220\openocd-esp32\bin\openocd.exe
File: ../src/jtag/core.c, Line 343
```

### Expected behavior

bring me to app_main

**Comment by suda-morris** [comment]
Hi @suskach I guess you haven't put [this file](https://github.com/espressif/openocd-esp32/blob/master/contrib/60-openocd.rules) to `/etc/udev/rules.d`.

**Comment by suskach** [comment]
Did you paid attention ?
It look like windows do not have udev/rules on Windows.
Tak you provide me solution for the Windows 10 ?

**Comment by erhankur** [comment]
@suskach Can you check this [comment](https://github.com/espressif/openocd-esp32/issues/230#issuecomment-1134393392) please?

**Comment by pravinkpatel** [comment]
Same issue facing

Open On-Chip Debugger  v0.11.0-esp32-20211220 (2021-12-20-15:43)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
adapter speed: 20000 kHz

Flashing D:/ESP/Projects/softAP/build/partition_table/partition-table.bin at 0x8000
Error: no device found
Error: unable to open ftdi device with vid 0403, pid 6010, description '*', serial '*' at bus location '*'
Error: no device found
Error: unable to open ftdi device with vid 0403, pid 6014, description '*', serial '*' at bus location '*'
** OpenOCD init failed **
shutdown command invoked
** Flashing Failed **
-1
Started by GNU MCU Eclipse
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Assertion failed!

Program: D:\Espressif\tools\openocd-esp32\v0.11.0-esp32-20211220\openocd-esp32\bin\openocd.exe
File: ../src/jtag/core.c, Line 343

Expression: jtag_trst == 0

**Comment by erhankur** [comment]
@pravinkpatel did you check if the driver is installed correctly?  https://github.com/espressif/openocd-esp32/issues/230#issuecomment-1134393392

**Comment by WangShuoran** [comment]
我有类似的问题，我的驱动绝对安装正确了，依然有问题，你可以试试用纯净的系统安装IDF(使用官方的安装器)，并安装对应版本的vscode插件，可以看看是否会出现相同的问题，因为我这样操作后不论ESP32C3，ESP32S3，和他们是否使用ESP-PROG或者使用内置JTAG，都完全进不了JTAG调试，甚至使用ESP-PROG都不能通过ESP-PROG下载程序
I have a similar problem. My driver is absolutely installed correctly, but there is still a problem. You can try installing IDF (using the official installer) on a pure system and install the corresponding version of vscode plug-in to see if the same problem will occur. Because after I do this, no matter whether esp32c3 or esp32s3, or whether they use esp-prog or use built-in JTAG, JTAG debugging is completely impossible, You can't even use esp-prog to download programs through esp-prog

**Comment by gerekon** [comment]
@WangShuoran 

Could you post OpenOCD logs?

**Comment by suskach** [comment]
hi , thanks for reply it look like after installing correct usb driver , I need to run opeocdd from administrATIVE CMD WINDOW.
tHANKS, LET HAVE THIS ISSUE CLOSED.

sERGEY

**Comment by WangShuoran** [comment]
Info : accepting 'tcl' connection on tcp/6666
Flashing d:/test_study/csi/csi_send/build/partition_table/partition-table.bin at 0x8000
Info : JTAG tap: esp32c3.cpu tap/device found: 0x00005c25 (mfg: 0x612 (Espressif Systems), part: 0x0005, ver: 0x0)
❌ Error: Algorithm timed out after 40001 ms.
❌ Error: ra = 0x40383c14
❌ Error: sp = 0x3fc847b0
❌ Error: gp = 0x0
❌ Error: tp = 0x0
❌ Error: t0 = 0x0
❌ Error: t1 = 0x40383bf0
❌ Error: t2 = 0x0
❌ Error: s0 = 0x3fc95000
❌ Error: s1 = 0x1702aa49
❌ Error: a0 = 0x1dc01f3
❌ Error: a1 = 0x0
❌ Error: a2 = 0x4
❌ Error: a3 = 0xed00f8
❌ Error: a4 = 0xea00f8
❌ Error: a5 = 0xf200f7
❌ Error: a6 = 0x0
❌ Error: a7 = 0x403816e4
❌ Error: s2 = 0x66
❌ Error: s3 = 0x1
❌ Error: s4 = 0x3
❌ Error: s5 = 0x0
❌ Error: s6 = 0x0
❌ Error: s7 = 0xa0
❌ Error: s8 = 0x0
❌ Error: s9 = 0xa0
❌ Error: s10 = 0x14
❌ Error: s11 = 0x8
❌ Error: t3 = 0x0
❌ Error: t4 = 0x0
❌ Error: t5 = 0x0
❌ Error: t6 = 0x0
❌ Error: pc = 0x403803da
❌ Error: mstatus = 0x201800
❌ Error: mepc = 0x0
❌ Error: mcause = 0x0
Error: Failed to wa❌ it algorithm (-302)!
Error: Algorithm run failed (-302)!
Error: Failed to run flasher stub (-302)!
Warn : Failed to get flash mappings (-302)!
❌ Error: Target is already running an algorithm
Error: Failed to start algori❌ thm (-4)!
Error: Failed to run flasher stub (-4)!
❌ Error: Target is already running an algorithm
Error: Failed to sta❌ rt algorithm (-4)!
Error: Failed to run flasher stub (-4)!
Error: Failed to probe flash, size 0 KB
Error: auto_probe failed
Error: Failed to find bank 'esp32c3.flash'!
** Flashing Failed **
-1


> @WangShuoran
> 
> Could you post OpenOCD logs?
