### ISSUE TITLE
ESP32S2 OpenOCD issue (OCD-614)

### ISSUE THREAD

**Issue by sapanshah-eaton** [espressif/openocd-esp32#242]
### Development Kit

ESP32-S2-DevKitM-1

### Module or chip used

ESP32S2

### Debug Adapter

JLINK

### OpenOCD version

v0.11.0-esp32-20211220

### Operating System

FreeRTOS

### Using an IDE ?

Eclipse

### OpenOCD command line

openocd.exe -f board/esp32s2-bridge.cfg -c "program_esp C:/Users/e0629509/Smart_Signaling/build/esp32_sample_app.bin 0x1000 verify exit"

### JTAG Clock Speed

1000

### ESP-IDF version

4.2

### Problem Description

C:\Users\e0629509\.espressif\workspace\Sapan\NextGen>C:\Users\e0629509\.espressif\tools\openocd-esp32\v0.11.0-esp32-20211220\openocd-esp32\bin\openocd.exe -f board/esp32s2-bridge.cfg -c "program_esp C:/Users/e0629509/Smart_Signaling/build/esp32_sample_app.bin 0x1000 verify exit"
Open On-Chip Debugger  v0.11.0-esp32-20211220 (2021-12-20-15:43)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
DEPRECATED! use 'adapter driver' not 'interface'
Info : J-Link Ultra V5 compiled Aug 24 2020 10:18:43
Info : Hardware version: 5.00
Info : VTarget = 3.288 V
Info : clock speed 1000 kHz
Info : JTAG tap: esp32s2.cpu tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : esp32s2: Target halted, PC=0x40000400, debug_reason=00000000
Info : Detected ESP32-S2 chip
Info : starting gdb server for esp32s2 on 3333
Info : Listening on port 3333 for gdb connections
Info : JTAG tap: esp32s2.cpu tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : esp32s2: Debug controller was reset.
Info : esp32s2: Core was reset.
Info : esp32s2: Target halted, PC=0x4001276A, debug_reason=00000000
Info : esp32s2: Core was reset.
Info : esp32s2: Target halted, PC=0x40000400, debug_reason=00000000
** Programming Started **
Info : esp32s2: Target halted, PC=0x40031E6E, debug_reason=00000001
Info : Flash mapping 0: 0x10020 -> 0x3f000020, 253 KB
Info : Flash mapping 1: 0x50020 -> 0x40080020, 896 KB
Info : esp32s2: Target halted, PC=0x40031E6E, debug_reason=00000001
Info : Auto-detected flash bank 'esp32s2.flash' size 4096 KB
Info : Using flash bank 'esp32s2.flash' size 4096 KB
Info : esp32s2: Target halted, PC=0x40031E6E, debug_reason=00000001
Info : Compressed 1282048 bytes to 751693 bytes in 0.050028s
Warn : not enough working area available(requested 44792)
Error: no working area available, can't alloc stub stack!
Error: Failed to run flasher stub (-308)!
Error: error writing to flash at address 0x00000000 at offset 0x00001000
** Programming Failed **
shutdown command invoked

### Debug Logs

```shell
C:\Users\e0629509\.espressif\workspace\Sapan\NextGen>C:\Users\e0629509\.espressif\tools\openocd-esp32\v0.11.0-esp32-20211220\openocd-esp32\bin\openocd.exe -f board/esp32s2-bridge.cfg -c "program_esp C:/Users/e0629509/Smart_Signaling/build/esp32_sample_app.bin 0x1000 verify exit"
Open On-Chip Debugger  v0.11.0-esp32-20211220 (2021-12-20-15:43)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
DEPRECATED! use 'adapter driver' not 'interface'
Info : J-Link Ultra V5 compiled Aug 24 2020 10:18:43
Info : Hardware version: 5.00
Info : VTarget = 3.288 V
Info : clock speed 1000 kHz
Info : JTAG tap: esp32s2.cpu tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : esp32s2: Target halted, PC=0x40000400, debug_reason=00000000
Info : Detected ESP32-S2 chip
Info : starting gdb server for esp32s2 on 3333
Info : Listening on port 3333 for gdb connections
Info : JTAG tap: esp32s2.cpu tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : esp32s2: Debug controller was reset.
Info : esp32s2: Core was reset.
Info : esp32s2: Target halted, PC=0x4001276A, debug_reason=00000000
Info : esp32s2: Core was reset.
Info : esp32s2: Target halted, PC=0x40000400, debug_reason=00000000
** Programming Started **
Info : esp32s2: Target halted, PC=0x40031E6E, debug_reason=00000001
Info : Flash mapping 0: 0x10020 -> 0x3f000020, 253 KB
Info : Flash mapping 1: 0x50020 -> 0x40080020, 896 KB
Info : esp32s2: Target halted, PC=0x40031E6E, debug_reason=00000001
Info : Auto-detected flash bank 'esp32s2.flash' size 4096 KB
Info : Using flash bank 'esp32s2.flash' size 4096 KB
Info : esp32s2: Target halted, PC=0x40031E6E, debug_reason=00000001
Info : Compressed 1282048 bytes to 751693 bytes in 0.050028s
Warn : not enough working area available(requested 44792)
Error: no working area available, can't alloc stub stack!
Error: Failed to run flasher stub (-308)!
Error: error writing to flash at address 0x00000000 at offset 0x00001000
** Programming Failed **
shutdown command invoked
```

### Expected behavior

It should program sucessfully.

### Screenshots

NA

**Comment by erhankur** [comment]
@sapanshah-eaton Can you attach verbose debug logs. See [item 3 here](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/jtag-debugging/tips-and-quirks.html#reporting-issues-with-openocd-gdb) for how to generate verbose logs.

Looks like esp32s2-bridge.cfg is modified. Can you share the modifications? 

And last can you try loading with program_esp_bins command?  You need to arrange the path for the build directory. e.g. 

```
openocd -f interface\jlink.cfg -f target\esp32s2.cfg -c "program_esp_bins build flasher_args.json reset compress verify exit"
```

**Comment by sapanshah-eaton** [comment]
This is esp32s2-bridge.cfg
--------------------------------------------------------------------------------------------------------
# Example OpenOCD configuration file for ESP32-S2 connected via ESP USB Bridge board
#
# For example, OpenOCD can be started for ESP32-S2 debugging on
#
#   openocd -f board/esp32s2-bridge.cfg
#

# Source the JTAG interface configuration file
#source [find interface/esp_usb_bridge.cfg]
source [find interface/jlink.cfg]
#transport select jtag

#adapter speed 1000
adapter_khz 1000

# ESP32S2 chip id defined in the idf esp_chip_model_t
#espusbjtag chip_id 2
# Source the ESP32-S2 configuration file
source [find target/esp32s2.cfg]
---------------------------------------------------------------------------
[openocd.txt](https://github.com/espressif/openocd-esp32/files/9380705/openocd.txt)

I have attached log file as well.

**Comment by sapanshah-eaton** [comment]
C:\Users\e0629509\.espressif\workspace\Sapan\NextGen>C:\Users\e0629509\.espressif\tools\openocd-esp32\v0.11.0-esp32-20211220\openocd-esp32\bin\openocd.exe -f interface/jlink.cfg -f board/esp32s2-bridge.cfg -c "program_esp_bins C:/Users/e0629509/Smart_Signaling/build flasher_args.json reset compress verify exit"
Open On-Chip Debugger  v0.11.0-esp32-20211220 (2021-12-20-15:43)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
DEPRECATED! use 'adapter driver' not 'interface'
DEPRECATED! use 'adapter driver' not 'interface'
Warn : Interface already configured, ignoring
DEPRECATED! use 'adapter speed' not 'adapter_khz'
invalid command name "program_esp_bins"

**Comment by erhankur** [comment]
Ok. I think I understand your issue. Your config file looks like mixed with the old  version. To get rid of work area size problem you can remove compress option or better you can use the original one. 
https://github.com/espressif/openocd-esp32/blob/v0.11.0-esp32-20211220/tcl/target/esp32s2.cfg

I suggest you to remove and re-installl the OpenOCD package and use below command parameters to run with  the Jlink. 

```
$OOCD_DIR/src/openocd -s $OOCD_DIR/tcl -f interface/jlink.cfg -f target/esp32s2.cfg
```

**Comment by sapanshah-eaton** [comment]
With above, I am getting below error.

C:\Users\e0629509\.espressif\workspace\Sapan\NextGen>C:\Users\e0629509\.espressif\tools\openocd-esp32\openocd-esp32-win32-0.11.0-esp32-20220706\openocd-esp32\bin\openocd.exe -s $OOCD_DIR/tcl -f interface/jlink.cfg -f target/esp32s2.cfg
Open On-Chip Debugger  v0.11.0-esp32-20220706 (2022-07-06-15:48)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Info : auto-selecting first available session transport "jtag". To override use 'transport select <transport>'.
RCLK - adaptive

Warn : Transport "jtag" was already selected
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : J-Link Ultra V5 compiled Aug 24 2020 10:18:43
Info : Hardware version: 5.00
Info : VTarget = 3.288 V
Info : RCLK (adaptive clock speed)
Info : JTAG tap: esp32s2.cpu tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Warn : Failed to receive data from device: LIBUSB_ERROR_TIMEOUT.
Warn : Failed to receive data from device: LIBUSB_ERROR_TIMEOUT.
Warn : Failed to receive data from device: LIBUSB_ERROR_TIMEOUT.
Error: Receiving data from device timed out.
Error: transport_read() failed: timeout occurred.
Error: jaylink_jtag_io() failed: timeout occurred
Warn : Last read operation left 1344 bytes.
Warn : Failed to send data to device: LIBUSB_ERROR_TIMEOUT.
Error: Failed to send data to device: LIBUSB_ERROR_PIPE.
Error: transport_write() failed: unspecified error.
Error: jaylink_jtag_io() failed: unspecified error
Error: Failed to read ARs (-104)!
Info : [esp32s2] Target halted, PC=0x00000000, debug_reason=00000000
Warn : Last read operation left 2 bytes.
Error: Failed to send data to device: LIBUSB_ERROR_IO.
Error: transport_write() failed: unspecified error.
Error: jaylink_jtag_io() failed: unspecified error
Warn : Last read operation left 10 bytes.
Error: Failed to send data to device: LIBUSB_ERROR_IO.
Error: transport_write() failed: unspecified error.
Error: jaylink_jtag_io() failed: unspecified error
Error: Failed to exec JTAG queue!
Error: Failed to read debug stubs address location (-104)!
Warn : Last read operation left 10 bytes.
Error: Failed to send data to device: LIBUSB_ERROR_IO.
Error: transport_write() failed: unspecified error.
Error: jaylink_jtag_io() failed: unspecified error
Warn : [esp32s2] Failed writing 4 bytes at address 0x3f41f064
Error: Failed to write ESP32_S2_TIMG0WDT_PROTECT (-104)!
Warn : Last read operation left 35 bytes.
Error: Failed to send data to device: LIBUSB_ERROR_IO.
Error: transport_write() failed: unspecified error.
Error: jaylink_jtag_io() failed: unspecified error
Warn : Last read operation left 8 bytes.
Error: Failed to send data to device: LIBUSB_ERROR_IO.
Error: transport_write() failed: unspecified error.
Error: jaylink_jtag_io() failed: unspecified error
Error: Failed to exec JTAG queue!
Error: Failed to read debug stubs address location (-104)!
Polling target esp32s2 failed, trying to reexamine
Warn : Last read operation left 10 bytes.
Error: Failed to send data to device: LIBUSB_ERROR_IO.
Error: transport_write() failed: unspecified error.
Error: jaylink_jtag_io() failed: unspecified error
Examination failed, GDB will be halted. Polling again in 100ms
Warn : Last read operation left 17 bytes.
Error: Failed to send data to device: LIBUSB_ERROR_IO.
Error: transport_write() failed: unspecified error.
Error: jaylink_jtag_io() failed: unspecified error
Warn : Last read operation left 27 bytes.
Error: Failed to send data to device: LIBUSB_ERROR_IO.
Error: transport_write() failed: unspecified error.
Error: jaylink_jtag_io() failed: unspecified error
Warn : Last read operation left 8 bytes.
Error: Failed to send data to device: LIBUSB_ERROR_IO.
Error: transport_write() failed: unspecified error.
Error: jaylink_jtag_io() failed: unspecified error
Error: Failed to exec JTAG queue!
Error: Failed to read debug stubs address location (-104)!
Polling target esp32s2 failed, trying to reexamine
Warn : Last read operation left 10 bytes.
Error: Failed to send data to device: LIBUSB_ERROR_IO.
Error: transport_write() failed: unspecified error.
Error: jaylink_jtag_io() failed: unspecified error
Examination failed, GDB will be halted. Polling again in 300ms
Info : starting gdb server for esp32s2 on 3333
Info : Listening on port 3333 for gdb connections
Warn : Last read operation left 17 bytes.
Error: Failed to send data to device: LIBUSB_ERROR_IO.
Error: transport_write() failed: unspecified error.
Error: jaylink_jtag_io() failed: unspecified error
Warn : Last read operation left 8 bytes.
Error: Failed to send data to device: LIBUSB_ERROR_IO.
Error: transport_write() failed: unspecified error.
Error: jaylink_jtag_io() failed: unspecified error
Error: Failed to exec JTAG queue!
Error: Failed to read debug stubs address location (-104)!
Polling target esp32s2 failed, trying to reexamine
Warn : Last read operation left 10 bytes.
Error: Failed to send data to device: LIBUSB_ERROR_IO.
Error: transport_write() failed: unspecified error.
Error: jaylink_jtag_io() failed: unspecified error
Examination failed, GDB will be halted. Polling again in 700ms
Warn : Last read operation left 17 bytes.
Error: Failed to send data to device: LIBUSB_ERROR_IO.
Error: transport_write() failed: unspecified error.
Error: jaylink_jtag_io() failed: unspecified error
Warn : Last read operation left 8 bytes.
Error: Failed to send data to device: LIBUSB_ERROR_IO.
Error: transport_write() failed: unspecified error.
Error: jaylink_jtag_io() failed: unspecified error
Error: Failed to exec JTAG queue!
Error: Failed to read debug stubs address location (-104)!
Polling target esp32s2 failed, trying to reexamine
Warn : Last read operation left 10 bytes.
Error: Failed to send data to device: LIBUSB_ERROR_IO.
Error: transport_write() failed: unspecified error.
Error: jaylink_jtag_io() failed: unspecified error
Examination failed, GDB will be halted. Polling again in 1500ms
Warn : Last read operation left 17 bytes.
Error: Failed to send data to device: LIBUSB_ERROR_IO.
Error: transport_write() failed: unspecified error.
Error: jaylink_jtag_io() failed: unspecified error
Warn : Last read operation left 8 bytes.
Error: Failed to send data to device: LIBUSB_ERROR_IO.
Error: transport_write() failed: unspecified error.
Error: jaylink_jtag_io() failed: unspecified error
Error: Failed to exec JTAG queue!
Error: Failed to read debug stubs address location (-104)!
Polling target esp32s2 failed, trying to reexamine
Warn : Last read operation left 10 bytes.
Error: Failed to send data to device: LIBUSB_ERROR_IO.
Error: transport_write() failed: unspecified error.
Error: jaylink_jtag_io() failed: unspecified error
Examination failed, GDB will be halted. Polling again in 3100ms
shutdown command invoked
Warn : Last read operation left 17 bytes.
Error: Failed to send data to device: LIBUSB_ERROR_IO.
Error: transport_write() failed: unspecified error.
Error: jaylink_jtag_io() failed: unspecified error
Error: Failed to clear OCDDCR_ENABLEOCD!
Warn : Last read operation left 10 bytes.
Error: Failed to send data to device: LIBUSB_ERROR_IO.
Error: transport_write() failed: unspecified error.
Error: jaylink_unregister() failed: unspecified error

**Comment by erhankur** [comment]
Please share the verbose logs with -d3. 

Did you add `adapter speed 1000` to the jlink.cfg?

**Comment by sapanshah-eaton** [comment]
I have added adapter speed 1000 in the jlink.cfg

I have attached log as well.
[open_ocd_log.txt](https://github.com/espressif/openocd-esp32/files/9424128/open_ocd_log.txt)

**Comment by sapanshah-eaton** [comment]
I have used jtag_rclk for speed. I have changed to adapter speed 1000. 
Below is the output. 

![image](https://user-images.githubusercontent.com/92917465/186653229-f1dc2ea0-8d58-4087-90e9-afb610aeb321.png)

**Comment by sapanshah-eaton** [comment]
[open_ocd_log.txt](https://github.com/espressif/openocd-esp32/files/9424190/open_ocd_log.txt)

**Comment by erhankur** [comment]
Then we should see `Info : clock speed 1000 kHz` in the log. I couldn't see this line.  

Please set it with  `adapter speed` command.  

Another option; 

$OOCD_DIR/src/openocd -s $OOCD_DIR/tcl -f interface/jlink.cfg -f target/esp32s2.cfg -c "adapter speed 1000"

**Comment by erhankur** [comment]
Ok. I can see, communication problem has been fixed. What is the problem now?

**Comment by sapanshah-eaton** [comment]
Eclipse does not load symbols and map break point with source file.

![image](https://user-images.githubusercontent.com/92917465/186668042-5cbbde72-649d-4914-bfec-1f02bd645c96.png)

**Comment by sapanshah-eaton** [comment]
another issue along with this is

Debug: 35480 50723 target.c:2466 target_write_buffer(): writing buffer of 2 byte at 0x40086bc3
Warn : 35481 50723 xtensa.c:1693 xtensa_write_memory(): address 0x40086bc3 not writable
Error: 35482 50723 xtensa.c:1929 xtensa_sw_breakpoint_add(): esp32s2: Failed to write breakpoint instruction (-4)!
Error: 35483 50723 xtensa.c:1964 xtensa_breakpoint_add(): esp32s2: Failed to add SW breakpoint!
[open_ocd_log.txt](https://github.com/espressif/openocd-esp32/files/9432298/open_ocd_log.txt)

Error: 35484 50723 breakpoints.c:92 breakpoint_add_internal(): can't add breakpoint: unknown reason
[open_ocd_log.txt](https://github.com/espressif/openocd-esp32/files/9432303/open_ocd_log.txt)

**Comment by sapanshah-eaton** [comment]
with vs code i am facing the same issue. 

![image](https://user-images.githubusercontent.com/92917465/186933438-23a4cbe7-3060-459b-a310-58bae4f9fcd2.png)

At least in VS code, it is loading code. 

Could you please help me?

**Comment by gerekon** [comment]
> another issue along with this is
> 
> Debug: 35480 50723 target.c:2466 target_write_buffer(): writing buffer of 2 byte at 0x40086bc3 Warn : 35481 50723 xtensa.c:1693 xtensa_write_memory(): address 0x40086bc3 not writable Error: 35482 50723 xtensa.c:1929 xtensa_sw_breakpoint_add(): esp32s2: Failed to write breakpoint instruction (-4)! Error: 35483 50723 xtensa.c:1964 xtensa_breakpoint_add(): esp32s2: Failed to add SW breakpoint! [open_ocd_log.txt](https://github.com/espressif/openocd-esp32/files/9432298/open_ocd_log.txt)
> 
> Error: 35484 50723 breakpoints.c:92 breakpoint_add_internal(): can't add breakpoint: unknown reason [open_ocd_log.txt](https://github.com/espressif/openocd-esp32/files/9432303/open_ocd_log.txt)

It looks like IDEs use very old version of OpenOCD `v0.10.0-esp32-20200709`. What ESP-IDF version do you use?
```
Debug: 9 18 options.c:246 add_default_dirs(): exepath=C:/Users/e0629509/.espressif/tools/openocd-esp32/v0.10.0-esp32-20200709/openocd-esp32/bin
Debug: 10 18 options.c:247 add_default_dirs(): bin2data=../share/openocd
Debug: 11 18 configuration.c:44 add_script_search_dir(): adding C:\Users\e0629509\.espressif\tools\openocd-esp32\v0.10.0-esp32-20200709\openocd-esp32\share\openocd\scripts
Debug: 12 18 configuration.c:44 add_script_search_dir(): adding C:/Users/e0629509/AppData/Roaming/OpenOCD
Debug: 13 18 configuration.c:44 add_script_search_dir(): adding C:/Users/e0629509/.espressif/tools/openocd-esp32/v0.10.0-esp32-20200709/openocd-esp32/bin/../share/openocd/site
Debug: 14 18 configuration.c:44 add_script_search_dir(): adding C:/Users/e0629509/.espressif/tools/openocd-esp32/v0.10.0-esp32-20200709/openocd-esp32/bin/../share/openocd/scripts
```
@kolipakakondal, @brianignacio5 Could you help to setup IDEs with the latest ESP-IDF?
