### ISSUE TITLE
OpenOCD cannot get flash map when using mcuboot instead of esp-idf bootloader (OCD-621)

### ISSUE THREAD

**Issue by jaybuckeye06** [espressif/openocd-esp32#243]
### OpenOCD version

v0.11.0-esp32-20211220

### Operating System

Mac OS X

### Using an IDE ?

n/a

### OpenOCD command line

openocd -f board/esp32-wrover-kit-3.3v.cfg -c "init; halt; esp32 appimage_offset 0x10000"

### ESP-IDF version

v4.2

### Problem Description

- When using esp-idf image format, openocd gets flash map just fine.

<img width="712" alt="Screen Shot 2022-08-29 at 12 48 31 AM" src="https://user-images.githubusercontent.com/90120048/187085403-bcf3b394-cf51-4688-a1d4-f1c4eee131a4.png">

- When using mcuboot, although the partition table keeps the same, openocd cannot find flash map.
<img width="714" alt="Screen Shot 2022-08-29 at 12 57 36 AM" src="https://user-images.githubusercontent.com/90120048/187085706-314bc847-725b-4ea5-a9ba-3a6df52b57ba.png">

_This is more of a feature request rather than an issue._

### Expected behavior

OpenOCD should be able to find the flash map no matter what bootloader is used.

**Comment by gerekon** [comment]
Hi @jaybuckeye06 

OpenOCD retrieves flash map from app image on flash. As far as I understand mcuboot uses different header format for app images on flash as compared to IDF bootloader. So I do not think this is a bug.

**Comment by erhankur** [comment]
Looks like in the near future, we do not have plans to support MCUboot image format. 

Also, AFAIK there is no table to get flash mapping from the image like we do for the IDF bootloader. It is written only in the linker.
