### ISSUE TITLE
Failed to lauch GDB: .pionit11 Error in sourced command files (OCD-697)

### ISSUE THREAD

**Issue by wilian-wagner** [espressif/openocd-esp32#268]
### Development Kit

Esp32 Devkit V4

### Module or chip used

Esp32 Wroom 32d'

### Debug Adapter

ESP-PROG

### OpenOCD version

Open On-Chip Debugger  v0.11.0-esp32-20220706

### Operating System

Windows

### Using an IDE ?

VSCode + platformio

### OpenOCD command line

debug

### JTAG Clock Speed

default

### ESP-IDF version

v5.0

### Problem Description

Using the VSCode, when i try to run and debug it sends the code then open a window error "Failed to lauch GDB: .pionit11 Error in sourced command files"

### Debug Logs

```shell
undefinedC:\Users\LAEPI\.platformio\packages\toolchain-xtensa-esp32\bin\xtensa-esp32-elf-gdb.exe: warning: Couldn't determine a path for the index cache directory.

Reading symbols from c:\Users\LAEPI\Documents\PlatformIO\Projects\Teste Serial debbug\.pio\build\upesy_wroom\firmware.elf...
PlatformIO Unified Debugger -> https://bit.ly/pio-debug
PlatformIO: debug_tool = esp-prog
PlatformIO: Initializing remote target...
Open On-Chip Debugger  v0.11.0-esp32-20220706 (2022-07-06-15:48)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
adapter speed: 20000 kHz

WARNING: boards/esp-wroom-32.cfg is deprecated, and may be removed in a future release.
adapter speed: 5000 kHz

Info : tcl server disabled
```

### Expected behavior

Expects to rum and see debug

### Screenshots

![image](https://user-images.githubusercontent.com/122545301/213265149-6cad84b6-95dc-4e88-a89b-4f0c5ba88dc0.png)

**Comment by erhankur** [comment]
Hi @wilian-wagner Can you share openocd verbose logs?  Explained [here](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/jtag-debugging/tips-and-quirks.html#reporting-issues-with-openocd-gdb)

I am not familiar with PIO platform. You may need to consult or create an issue there too.

**Comment by wilian-wagner** [comment]
[openocd_log.txt](https://github.com/espressif/openocd-esp32/files/10455925/openocd_log.txt)

I think it's this file, thanks in advance for your help!

**Comment by erhankur** [comment]
You have same issue with https://github.com/espressif/openocd-esp32/issues/159  Please check it and make sure  ftdi driver  is installed and ESP-PROG cable connection is ok.

```
Debug: 807 52 ftdi.c:654 ftdi_initialize(): ftdi interface using shortest path jtag state transitions
Error: 808 197 mpsse.c:206 open_matching_device(): no device found
Error: 809 197 mpsse.c:356 mpsse_open(): unable to open ftdi device with vid 0403, pid 6010, description '*', serial '*' at bus location '*'
Error: 810 212 mpsse.c:206 open_matching_device(): no device found
Error: 811 212 mpsse.c:356 mpsse_open(): unable to open ftdi device with vid 0403, pid 6014, description '*', serial '*' at bus location '*'
Debug: 812 213 command.c:545 run_command(): Command 'init' failed with error code -100
```

**Comment by erhankur** [comment]
@wilian-wagner any update?

**Comment by wilian-wagner** [comment]
Yep, i solved... After a lot of tryings i discover that the pid/vid number configurated in the librarys were different than mine...

**Comment by Tarek-Ragab-Abdelal** [comment]
@wilian-wagner  please can you guide me with configuring the pid/vid number? I am stuck at the same issue, but I have no clue how to resolve it
