### ISSUE TITLE
[TW#18925] Openocd reg command doesn't display register values

### ISSUE THREAD

**Issue by projectgus** [espressif/openocd-esp32#3]
When halted in gdb, `info reg` produces accurate register values but `mon reg` doesn't show anything, and `mon reg REGNAME` (ie `mon reg PC`) shows values as 0x00000000, even when gdb knows the correct value.

**Comment by projectgus** [comment]
Seems like the mon reg output is not always all-zeroes, although it often doesn't match the gdb register cache version.

**Comment by Spritetm** [comment]
That is because for whatever mysterious reason, the openocd monitor defaults to the app cpu. Do a ``targets esp32.cpu0`` before it and it should target the pro cpu instead.
