### ISSUE TITLE
Start openocd faild (OCD-867)

### ISSUE THREAD

**Issue by lingxd** [espressif/openocd-esp32#303]
### Development Kit

ESP32-C6-DevKitC-1

### Module or chip used

esp32-c6

### Debug Adapter

ESP-PROG

### OpenOCD version

v0.12.0-esp32-20230921

### Operating System

Linux

### Using an IDE ?

vscode

### OpenOCD command line

/home/ubun/.espressif/tools/openocd-esp32/v0.12.0-esp32-20230921/openocd-esp32/bin/openocd    I click start openocd on the vscode status bar

### JTAG Clock Speed

default

### ESP-IDF version

release 5.1.2

### Problem Description

![image](https://github.com/espressif/openocd-esp32/assets/27987136/9a5c1f4d-50f0-490c-aac7-ac1baf8d4200)
![image](https://github.com/espressif/openocd-esp32/assets/27987136/f9588d57-991f-4c64-ab55-9939e41bf4d9)
![image](https://github.com/espressif/openocd-esp32/assets/27987136/92c9f7ab-2d21-4ab3-84e5-cd10037dc3c7)

### Debug Logs

```shell
/home/ubun/.espressif/tools/openocd-esp32/v0.12.0-esp32-20230921/openocd-esp32/bin/openocd

[OpenOCD]
Open On-Chip Debugger v0.12.0-esp32-20230921 (2023-09-21-13:41)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
debug_level: 2

[OpenOCD]
Info : auto-selecting first available session transport "jtag". To override use 'transport select <transport>'.

[OpenOCD]
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections

[OpenOCD]
❌ Error: unable to open ftdi device with description '*', serial '*' at bus location '*'

[OpenOCD]
❌ /home/ubun/.espressif/tools/openocd-esp32/v0.12.0-esp32-20230921/openocd-esp32/share/openocd/scripts/target/esp_common.cfg:9: Error: 
at file "/home/ubun/.espressif/tools/openocd-esp32/v0.12.0-esp32-20230921/openocd-esp32/share/openocd/scripts/target/esp_common.cfg", line 9

[OpenOCD]
[Stopped] : OpenOCD Server
```

### Expected behavior

Successfully started openocd

**Comment by deeyonn** [comment]
I am having this issue as well on windows.

```
[OpenOCD]
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
❌ Error: esp_usb_jtag: could not find or open device!
❌ ~\.espressif\tools\openocd-esp32\v0.12.0-esp32-20230921/openocd-esp32/share/openocd/scripts/target/esp_common.cfg:9: Error: at file "~\.espressif\tools\openocd-esp32\v0.12.0-esp32-20230921/openocd-esp32/share/openocd/scripts/target/esp_common.cfg", line 9
[Stopped] : OpenOCD Server

[Flash]
Can't perform JTag flash, because OpenOCD server is not running!
```
`settings.json`
![image](https://github.com/espressif/openocd-esp32/assets/41563700/aaf55a70-f4ce-458e-b194-36fce3a8debc)

**Comment by erhankur** [comment]
Probably because your `openOcdConfigs` is wrong.  Try `board/esp32c6-builtin.cfg` instead of `board/esp32c6-bridge.cfg` 

Bridge config files prepared for the ESP-USB-Bridge hardware. https://github.com/espressif/esp-usb-bridge

**Comment by erhankur** [comment]
According to the logs you have a driver issue. 

You can check here for the driver installation. https://github.com/espressif/idf-installer

**Comment by emb4fun** [comment]
What kind of board you are using? Here I had the same problem with a ESP32-C6 board where only one USB port was available. That mean an USB hub was available on this board.

I now used a board where the UART USB and JTAG USB port are separated, and here I do not have this kind of problems.

Could this be your problem too?

**Comment by deeyonn** [comment]
My issue was the manufacturer did not solder the jumper pins for me, so I got a replacement.
