### ISSUE TITLE
ESP32-C3 not mentioned in the README - intentional? (OCD-882)

### ISSUE THREAD

**Issue by lure23** [espressif/openocd-esp32#313]
### Development Kit

ESP32-C3-DevKitC-02

### Module or chip used

ESP32-C3-WROOM-02

### Debug Adapter

na

### OpenOCD version

master

### Operating System

na

### Using an IDE ?

na

### OpenOCD command line

na

### JTAG Clock Speed

na

### ESP-IDF version

na

### Problem Description

The `README` does not mention ESP32-C3: https://github.com/espressif/openocd-esp32/blob/master/README#L125

Is this intentional?

### Expected behavior

At least before merging to upstream, it would be good that all supported ESP32 boards are listed.

**Comment by erhankur** [comment]
Not exactly. It contains only the upstreamed device list. I will add the others like ESP32-C2, C3, C6, H2 and upcoming P4

Thanks for pointing out.
