### ISSUE TITLE
[TW#20232] olimex-arm-usb-tiny-h JATG

### ISSUE THREAD

**Issue by snahmad** [espressif/openocd-esp32#33]
Hi,

I am using olimex-arm-usb-tiny-h.

https://www.olimex.com/forum/index.php?topic=236.0

"The drivers can be downloaded directly from:
https://www.olimex.com/Products/ARM/JTAG/_resources/OpenOCD_OnlinePackage_v1.1.zip

I do this below command. nothing happens no output.

./openocd-libftdi.exe -s share/openocd/scripts -f share/openocd/scripts/interface/olimex-arm-usb-tiny-h.cfg -f share/openocd/scripts/board/esp-wroom-32.cfg

Any idea why?

Thanks,
Naeem

**Comment by igrr** [comment]
Please check that you are running OpenOCD compiled from this project. From your command line, it seems that you are running `openocd-libftdi.exe`, which comes from Olimex package instead.

You can download a binary from releases page of this project.
