### ISSUE TITLE
[TW#20236] fail to build openocd

### ISSUE THREAD

**Issue by jictannu** [espressif/openocd-esp32#34]
When building openocd with MSYS2, the build process fails with following message:

Making all in doc
make[2]: Entering directory“/home/Y400/esp/openocd-esp32/doc”
restore=: && backupdir=".am$$" && \
am__cwd=`pwd` && CDPATH="${ZSH_VERSION+.}:" && cd . && \
rm -rf $backupdir && mkdir $backupdir && \
if (makeinfo --version) >/dev/null 2>&1; then \
  for f in openocd.info openocd.info-[0-9] openocd.info-[0-9][0-9] openocd.i[0-9] openocd.i[0-9][0-9]; do \
    if test -f $f; then mv $f $backupdir; restore=mv; else :; fi; \
  done; \
else :; fi && \
cd "$am__cwd"; \
if makeinfo   -I . \
 -o openocd.info openocd.texi; \
then \
  rc=0; \
  CDPATH="${ZSH_VERSION+.}:" && cd .; \
else \
  rc=$?; \
  CDPATH="${ZSH_VERSION+.}:" && cd . && \
  $restore $backupdir/* `echo "./openocd.info" | sed 's|[^/]*$||'`; \
fi; \
rm -rf $backupdir; exit $rc
'penocd.texi:7986: unknown command `
'penocd.texi:7987: unknown command `
make[2]: *** [Makefile:383：openocd.info] Error  1
make[2]: Leaving directory“/home/Y400/esp/openocd-esp32/doc”
make[1]: *** [Makefile:513：all-recursive] Error  1
make[1]: Leaving directory“/home/Y400/esp/openocd-esp32”
make: *** [Makefile:421：all] Error  2

**Comment by igrr** [comment]
It seems that you don't have `makeinfo` command installed. Please run `apt-get install texinfo` or equivalent on your system.
