### ISSUE TITLE
OpenOCD debug failed with error: Error: 1125 1132 target.c:517 target_halt(): Target not examined yet (OCD-1044)

### ISSUE THREAD

**Issue by tradedn** [espressif/openocd-esp32#348]
### OpenOCD version

v0.12.0-esp32-20240318

### Operating System

Windows 11

### Using an IDE ?

Version: 3.1.0 Build id: 20241007-0706

### OpenOCD command line

-s C:\Espressif\tools\openocd-esp32\v0.12.0-esp32-20240318\openocd-esp32\share\openocd\scripts -f interface/ftdi/esp32_devkitj_v1.cfg -f target/esp32s3.cfg

### ESP-IDF version

esp-idf-v5.2.2

### Problem Description

Use the Espressif IDE to debug software with ESP prog board, connect the uart and jtag pin as written in manual 
https://docs.espressif.com/projects/esp-iot-solution/en/latest/hw-reference/ESP-Prog_guide.html

### Debug Logs

```shell
Info : 1114 1131 server.c:90 add_connection(): accepting 'gdb' connection on tcp/3333
Debug: 1115 1131 breakpoints.c:328 breakpoint_remove_all_inter
nal(): [esp32s3.cpu0] Delete all breakpoints
Debug: 1116 1131 breakpoints.c:328 breakpoint_remove_all_internal(): [esp32s3.cpu1] Delete all breakpoints
Debug: 1117 1131 breakpoints.c:655 watchpoint_clear_target(): Delete all watchpoints for target: esp32s3.cpu0
Debug: 1118 1131 target.c:1781 target_call_event_callbacks(): target event 22 (gdb-attach) for core esp32s3.cpu0
Debug: 1119 1131 target.c:4679 target_handle_event(): target: esp32s3.cpu0 (esp32s3) event: 22 (gdb-attach) action: 
		if { $_ESP_SMP_BREAK != 0 } {
			$_TARGETNAME_0 xtensa smpbreak BreakIn BreakOut
		}
		# necessary to auto
-probe flash bank when GDB is connected and generate proper memory map
		halt 1000
		if { [$_ESP_MEMPROT_IS_ENABLED] } {
			# 'reset halt' to disable memory protection and allow flasher to work correctly
			echo "Memory protection is enabled. Reset target to disable it..."
			reset halt
		}

		if { $_ESP_ARCH == "riscv" } {
			# by default mask interrupts while stepping
			riscv set_maskisr steponly
		}
	
Debug: 1120 1132 command.c:152 script_debug(): command - esp32s3.cpu0 xtensa smpbreak BreakIn BreakOut
Debug: 1121 1132 xtensa.c:886 xtensa_smpbreak_set(): [esp32s3.cpu0] set smpbreak=30000, state=1
Debug: 1122 1132 xtensa.c:886 xtensa_smpbreak_set(): [esp32s3.cpu1] set smpbreak=30000, state=1
Debug: 1123 1132 command.c:152 script_debug(): command - halt 1000
Debug: 1124 1132 target.c:3251 handle_halt_command(): -
Error: 1125 1132 target.c:517 target_halt(): Target not examined yet
Please refer to the troubleshooting guide below to identify the problem.
https://github.com/espressif/openocd-esp32/wiki/Troubleshooting-FAQ
Debug: 1126 1133 command.c:528 exec_command(): Command 'halt' failed with error code -4
User : 1127 1133 target.c:470
4 target_handle_event(): Error executing event gdb-attach on target esp32s3.cpu0:
embedded:startup.tcl:1561: Error: 
in procedure 'program_esp' called at file "C:\Espressif\tools\openocd-esp32\v0.12.0-esp32-20240318\openocd-esp32\share\openocd\scripts/target/esp_common.cfg", line 562
in procedure 'program_error' called at file "C:\Espressif\tools\openocd-esp32\v0.12.0-esp32-20240318\openocd-esp32\share\openocd\scripts/target/esp_common.cfg", line 395
at file "embedded:startup.tcl", line 1561
Debug: 1128 1133 FreeRTOS.c:1404 freertos_clean(): freertos_clean
Debug: 1129 1133 FreeRTOS.c:899 freertos_update_threads(): freertos_update_threads
Warn : 1130 1133 FreeRTOS.c:907 freertos_update_threads(): No symbols for FreeRTOS!
Error: 1131 1134 esp_flash.c:952 esp_algo_flash_probe(): Target not halted
Please refer to the troubleshooting guide below to identify the problem.
https://github.com/espressif/openocd-esp32/wiki/Troubleshooting-FAQ
Error: 1132 1134 core.c:291 get_flash_bank_by_num(): auto_probe failed
Please refer to the troubleshooting guide below to identify the problem.
https://github.com/espressif/openocd-esp32/wiki/Troubleshooting-FAQ
Error: 1133 1134 gdb_server.c:1052 gdb_new_connection(): Connect failed. Consider setting up a gdb-attach event for the target to prepare target for GDB connect, or use 'gdb_memory_map disable'.
Please refer to the troubleshooting guide below to identify the problem.
https://github.com/espressif/openocd-esp32/wiki/Troubleshooting-FAQ
Error: 1134 1134 server.c:94 add_connection(): attempted 'gdb' connection rejected
Please refer to the troubleshooting guide below to identify the problem.
https://github.com/espressif/openocd-esp32/wiki/Troubleshooting-FAQ
Debug: 1135 1146 server.c:607 sig_handler(): Terminating on Signal 2
Debug: 1136 1202 command.c:152 script_de
bug(): command - shutdown
User : 1137 1202 server.c:758 h
a
ndle_shutdown_command(): shutdown command invoked
Debu
g: 1138 1202 breakpoints.c:328 breakpoint_remove_all_internal(): [esp32s3.cpu0] Delete all breakpoints
Debug: 1139 1202 breakpoints.c:328 breakpoint_remove_all_internal(): [esp32s3.cpu1] Delete all breakpoints
Debug: 1140 1202 esp_xtensa.c:198 esp_xtensa_target_deinit(): start
Debug: 1141 1202 xtensa.c:3423 xtensa_target_deinit(): start
Debug: 1142 1203 target.c:2135 target_free_all_working_areas_restore(): freeing all working areas
Debug: 1143 1203 breakpoints.c:328 breakpoint_remove_all_internal(): [esp32s3.cpu1] Delete all breakpoints
Debug: 1144 1203 esp_xtensa.c:198 esp_xtensa_target_deinit(): start
Debug: 1145 1203 xtensa.c:3423 xtensa_target_deinit(): start
Debug: 1146 1204 target.c:2135 target_free_all_working_areas_restore(): freeing all working areas
```

### Expected behavior

Get an online debug via the OpenOCD

**Comment by tradedn** [comment]
The configuration is:

![Screenshot 2024-11-25 111726](https://github.com/user-attachments/assets/055d4169-586c-4945-9210-5ecd18e56df7)

**Comment by tradedn** [comment]
![Screenshot 2ddd024-11-26 094356](https://github.com/user-attachments/assets/6c4f1888-33e2-4c9c-aba3-80f61a3a404a)

![image](https://github.com/user-attachments/assets/abfd6d61-4e89-4b6b-9902-7fee4df40926)

**Comment by erhankur** [comment]
@tradedn  Could you share all logs before the error line ?

`Error: 1125 1132 target.c:517 target_halt(): Target not examined yet` 

Did you burn the efuse to use jtag pins?

https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-guides/jtag-debugging/configure-other-jtag.html#configure-efuses

**Comment by tradedn** [comment]
> @tradedn Could you share all logs before the error line ?
> 
> `Error: 1125 1132 target.c:517 target_halt(): Target not examined yet`
> 
> Did you burn the efuse to use jtag pins?
> 
> https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-guides/jtag-debugging/configure-other-jtag.html#configure-efuses

Yes, I'd like to do it and if you can tell me how to record the whole log into a file, it would be appriciated
By the way, I don't burn the efuse currently

**Comment by tradedn** [comment]
@erhankur Many thanks to you, I'll try it and get the full log back to you soon

**Comment by tradedn** [comment]
@erhankur I read the url and have a try and I get the following log:

PS C:\Espressif\tools\openocd-esp32\v0.12.0-esp32-20240318\openocd-esp32\share\openocd\scripts> openocd -f .\board\esp32c3-builtin.cfg
Open On-Chip Debugger v0.12.0-esp32-20240318 (2024-03-18-18:26)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Info : only one transport option; autoselecting 'jtag'
Info : esp_usb_jtag: VID set to 0x303a and PID to 0x1001
Info : esp_usb_jtag: capabilities descriptor set to 0x2000
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Error: esp_usb_jtag: could not find or open device!
target/esp_common.cfg:9: Error:
at file "target/esp_common.cfg", line 9
Error: [esp32c3] Unsupported DTM version: -1
Error: [esp32c3] Could not identify target type.
PS C:\Espressif\tools\openocd-esp32\v0.12.0-esp32-20240318\openocd-esp32\share\openocd\scripts>
PS C:\Espressif\tools\openocd-esp32\v0.12.0-esp32-20240318\openocd-esp32\share\openocd\scripts>
### **PS C:\Espressif\tools\openocd-esp32\v0.12.0-esp32-20240318\openocd-esp32\share\openocd\scripts> openocd -f .\board\esp32c3-ftdi.cfg**
Open On-Chip Debugger v0.12.0-esp32-20240318 (2024-03-18-18:26)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Info : auto-selecting first available session transport "jtag". To override use 'transport select <transport>'.
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : ftdi: if you experience problems at higher adapter clocks, try the command "ftdi tdo_sample_edge falling"
Info : clock speed 20000 kHz
Error: JTAG scan chain interrogation failed: all ones
Error: Check JTAG interface, timings, target power, etc.
Error: Trying to use configured scan chain anyway...
Error: esp32c3.cpu: IR capture error; saw 0x1f not 0x01
Warn : Bypassing JTAG setup events due to errors
Error: [esp32c3] Unsupported DTM version: 15
Error: [esp32c3] Examination failed
Warn : target esp32c3 examination failed
Info : starting gdb server for esp32c3 on 3333
Info : Listening on port 3333 for gdb connections


And the GPIO3 in my board is used by the SPI3_HOST to communicate with a peripheral device

**Comment by erhankur** [comment]
If you successfully burned the eFuse, you can also refer to here: https://github.com/espressif/openocd-esp32/wiki/Troubleshooting-FAQ#jtag-connection-is-bad

**Comment by tradedn** [comment]
> If you successfully burned the eFuse, you can also refer to here: https://github.com/espressif/openocd-esp32/wiki/Troubleshooting-FAQ#jtag-connection-is-bad

I don't burn the eFuse, I would like to deug via the jtag but failed with some error as I described.
I read the url, but I can't find a similar issue like I get

**Comment by tradedn** [comment]
PS C:\Espressif\tools\openocd-esp32\v0.12.0-esp32-20240318\openocd-esp32\share\openocd\scripts> openocd -f .\board\esp32s3-ftdi.cfg -c 'adapter speed 50'
Open On-Chip Debugger v0.12.0-esp32-20240318 (2024-03-18-18:26)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Info : auto-selecting first available session transport "jtag". To override use 'transport select <transport>'.
adapter speed: 50 kHz
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : clock speed 50 kHz
Info : TAP esp32s3.cpu0 does not have valid IDCODE (idcode=0x0)
Info : TAP esp32s3.cpu1 does not have valid IDCODE (idcode=0x0)
Info : TAP auto0.tap does not have valid IDCODE (idcode=0x0)
Info : TAP auto1.tap does not have valid IDCODE (idcode=0x0)
Info : TAP auto2.tap does not have valid IDCODE (idcode=0x0)
Info : TAP auto3.tap does not have valid IDCODE (idcode=0x0)
Info : TAP auto4.tap does not have valid IDCODE (idcode=0x0)
Info : TAP auto5.tap does not have valid IDCODE (idcode=0x0)
Info : TAP auto6.tap does not have valid IDCODE (idcode=0x0)
Info : TAP auto7.tap does not have valid IDCODE (idcode=0x0)
Info : TAP auto8.tap does not have valid IDCODE (idcode=0x0)
Info : TAP auto9.tap does not have valid IDCODE (idcode=0x0)
Info : TAP auto10.tap does not have valid IDCODE (idcode=0x0)
Info : TAP auto11.tap does not have valid IDCODE (idcode=0x0)
Info : TAP auto12.tap does not have valid IDCODE (idcode=0x0)
Info : TAP auto13.tap does not have valid IDCODE (idcode=0x0)
Info : TAP auto14.tap does not have valid IDCODE (idcode=0x0)
Info : TAP auto15.tap does not have valid IDCODE (idcode=0x0)
Info : TAP auto16.tap does not have valid IDCODE (idcode=0x0)
Info : TAP auto17.tap does not have valid IDCODE (idcode=0x0)
Info : TAP auto18.tap does not have valid IDCODE (idcode=0x0)
Warn : Unexpected idcode after end of chain: 21 0x00000000
Warn : Unexpected idcode after end of chain: 53 0x00000000
Warn : Unexpected idcode after end of chain: 85 0x00000000
Warn : Unexpected idcode after end of chain: 117 0x00000000
Warn : Unexpected idcode after end of chain: 149 0x00000000
Warn : Unexpected idcode after end of chain: 181 0x00000000
Warn : Unexpected idcode after end of chain: 213 0x00000000
Warn : Unexpected idcode after end of chain: 245 0x00000000
Warn : Unexpected idcode after end of chain: 277 0x00000000
Warn : Unexpected idcode after end of chain: 309 0x00000000
Warn : Unexpected idcode after end of chain: 341 0x00000000
Warn : Unexpected idcode after end of chain: 373 0x00000000
Warn : Unexpected idcode after end of chain: 405 0x00000000
Warn : Unexpected idcode after end of chain: 437 0x00000000
Warn : Unexpected idcode after end of chain: 469 0x00000000
Warn : Unexpected idcode after end of chain: 501 0xfffffe00
Error: double-check your JTAG setup (interface, speed, ...)
Error: Trying to use configured scan chain anyway...
Error: esp32s3.cpu0: IR capture error; saw 0x00 not 0x01
Warn : Bypassing JTAG setup events due to errors
Warn : [esp32s3.cpu0] Unexpected OCD_ID = 00000000
Error: [esp32s3.cpu0] Examination failed
Warn : target esp32s3.cpu0 examination failed
Warn : [esp32s3.cpu1] Unexpected OCD_ID = 00000000
Error: [esp32s3.cpu1] Examination failed
Warn : target esp32s3.cpu1 examination failed
Info : starting gdb server for esp32s3.cpu0 on 3333
Info : Listening on port 3333 for gdb connections

@erhankur  I change the clk speed from 20M to 50k and I get this log, what does it mean ?

**Comment by erhankur** [comment]
If you’re not using the ESP-PROG through the JTAG pins, it means you’re using the built-in USB-SERIAL-JTAG interface via the USB connector or D+, D- pins. https://docs.espressif.com/projects/esp-idf/en/v5.2.3/esp32s3/api-guides/jtag-debugging/configure-builtin-jtag.html#configure-esp32-s3-built-in-jtag-interface 

And your new OpenOCD config will be;
```
-s C:\Espressif\tools\openocd-esp32\v0.12.0-esp32-20240318\openocd-esp32\share\openocd\scripts -f board/esp32s3-builtin.cfg
```

If you didn't burn the efuse, you can only use builtin USB JTAG. 

Please describe your setup. I made assumption based on your OpenOCD config file but looks like it is not correct.

**Comment by tradedn** [comment]
### PS C:\Espressif\tools\openocd-esp32\v0.12.0-esp32-20240318\openocd-esp32\share\openocd\scripts> openocd -f interface\ftdi\esp32_devkitj_v1.cfg -f target\esp32s3.cfg -c 'adapter speed 1'
Open On-Chip Debugger v0.12.0-esp32-20240318 (2024-03-18-18:26)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
adapter speed: 20000 kHz
Info : auto-selecting first available session transport "jtag". To override use 'transport select <transport>'.
adapter speed: 1 kHz
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : clock speed 1 kHz
Info : TAP esp32s3.cpu0 does not have valid IDCODE (idcode=0xf0001f80)
Info : TAP esp32s3.cpu1 does not have valid IDCODE (idcode=0x78000fc0)
Info : TAP auto0.tap does not have valid IDCODE (idcode=0x3c0007e0)
Info : TAP auto1.tap does not have valid IDCODE (idcode=0x1e0003f0)
Info : TAP auto2.tap does not have valid IDCODE (idcode=0xf0001f8)
Info : TAP auto3.tap does not have valid IDCODE (idcode=0x78000fc)
Info : TAP auto4.tap does not have valid IDCODE (idcode=0x3c0007e)
Info : JTAG tap: auto5.tap tap/device found: 0x01e0003f (mfg: 0x01f (Atmel), part: 0x1e00, ver: 0x0)
Info : TAP auto6.tap does not have valid IDCODE (idcode=0xe0001e00)
Info : TAP auto7.tap does not have valid IDCODE (idcode=0xf0000f00)
Info : TAP auto8.tap does not have valid IDCODE (idcode=0x78000780)
Info : TAP auto9.tap does not have valid IDCODE (idcode=0x3c0003c0)
Info : TAP auto10.tap does not have valid IDCODE (idcode=0x1e0001e0)
Info : TAP auto11.tap does not have valid IDCODE (idcode=0xf0000f0)
Info : TAP auto12.tap does not have valid IDCODE (idcode=0x7800078)
Info : TAP auto13.tap does not have valid IDCODE (idcode=0x3c0003c)
Info : TAP auto14.tap does not have valid IDCODE (idcode=0x1e0001e)
Info : JTAG tap: auto15.tap tap/device found: 0x00f0000f (mfg: 0x007 (Hitachi), part: 0x0f00, ver: 0x0)
Info : TAP auto16.tap does not have valid IDCODE (idcode=0xf0000f00)
Info : TAP auto17.tap does not have valid IDCODE (idcode=0x78000780)
Info : TAP auto18.tap does not have valid IDCODE (idcode=0x3c0003c0)
Warn : Unexpected idcode after end of chain: 83 0x1e0001e0
Warn : Unexpected idcode after end of chain: 115 0x0001e000
Warn : Unexpected idcode after end of chain: 147 0x01e0001e
Warn : Unexpected idcode after end of chain: 179 0xe0001e00
Warn : Unexpected idcode after end of chain: 211 0x001e0001
Warn : Unexpected idcode after end of chain: 243 0x1e0001e0
Warn : Unexpected idcode after end of chain: 275 0x0001c000
Warn : Unexpected idcode after end of chain: 307 0x01c0001c
Warn : Unexpected idcode after end of chain: 339 0xc0001c00
Warn : Unexpected idcode after end of chain: 371 0x001c0001
Warn : Unexpected idcode after end of chain: 403 0x1c0001c0
Warn : Unexpected idcode after end of chain: 435 0x0001c000
Warn : Unexpected idcode after end of chain: 467 0x01c0001c
Warn : Unexpected idcode after end of chain: 499 0xc0001c00
Warn : Unexpected idcode after end of chain: 531 0x001c0001
Warn : Unexpected idcode after end of chain: 563 0x1c0001c0
Warn : Unexpected idcode after end of chain: 595 0x0001c000
Warn : Unexpected idcode after end of chain: 627 0x01c0001c
Error: double-check your JTAG setup (interface, speed, ...)
Error: Trying to use configured scan chain anyway...
Error: esp32s3.cpu0: IR capture error; saw 0x1c not 0x01
Warn : Bypassing JTAG setup events due to errors
Info : [esp32s3.cpu0] Examination succeed
Info : [esp32s3.cpu1] Examination succeed
Info : starting gdb server for esp32s3.cpu0 on 3333
Info : Listening on port 3333 for gdb connections
Info : [esp32s3.cpu0] Core was reset.
Info : [esp32s3.cpu1] Debug controller was reset.
Info : [esp32s3.cpu1] Core was reset.
Info : [esp32s3.cpu0] Debug controller was reset.
Info : [esp32s3.cpu1] Debug controller was reset.
Info : [esp32s3.cpu1] Debug controller was reset.
Error: [esp32s3.cpu1] Timed out waiting for CPU to be reset, target state=0
Error: [esp32s3.cpu1] Failed to wait for target halt to read reset cause (0)!
Polling target esp32s3.cpu1 failed, trying to reexamine
Info : [esp32s3.cpu1] Examination succeed
Info : [esp32s3.cpu1] Core was reset.
shutdown command invoked

 I'm using ESP-prog without burning the efuse.
According to this running log, my understanding is the software configuration and the jtag PIN connection are both right but
the jtag communication is not as good as my expectation due to some hareware signal issue, Is it right ?

**Comment by erhankur** [comment]
This is my bad, maybe i wasn't clear enough. I will try to explain once and last. 

You can not use ESP-PROG without burning one of the efuses!!!

Please read the docs first and come here again.

**Comment by tradedn** [comment]
I read the information in this url: 
https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-guides/jtag-debugging/configure-other-jtag.html
But I doubt that I may understand it wrong, anyway I'll try to brun the efuse and use the ESP-prog for debugging.
Thanks
