### ISSUE TITLE
WROVER-V3 does not 'continue' after mon reset

### ISSUE THREAD

**Issue by KampfCaspar** [espressif/openocd-esp32#39]
Whatever I try, after 'mon reset' nothing seems to run anymore... Even stopping openocd and trying to flash fails (no further reaction from the board). Without 'mon reset' however, it seems to work fine.

examples/get-started/blink with
esp-idf with tag v3.0
xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0
openocd-esp32-linux64-0.10.0-esp32-20180604

[gdb_log.txt](https://github.com/espressif/openocd-esp32/files/2073597/gdb_log.txt)
[openocd_log.txt](https://github.com/espressif/openocd-esp32/files/2073598/openocd_log.txt)

Is there anything I don't see?

**Comment by igrr** [comment]
Judging by the log this is the same issue as https://github.com/espressif/openocd-esp32/issues/38 (program is stuck in ROM code, at 0x40007ba1). Please follow the link and click "Subscribe" to receive further updates.
