### ISSUE TITLE
openocd on raspberry pi

### ISSUE THREAD

**Issue by yschaeff** [espressif/openocd-esp32#4]
I'm trying to compile openocd on a raspberry pi and I'm hitting this issue:

rtos_freertos_stackings.c: In function 'rtos_freertos_esp108_stack_read_voluntary':
rtos_freertos_stackings.c:375:22: error: cast increases required alignment of target type [-Werror=cast-align]
  uint32_t *stackregs=(uint32_t *)stack_data; //alias so we can read/write entire words. Little-endian hosts only!

Which make sense since the code mentions it doesn't work on big endian machines. I'd like to use a raspberry pi as JTAG adapter but I can't get it to compile.

**Comment by igrr** [comment]
One line above there's a workaround which is currently enabled only in clang:
https://github.com/espressif/openocd-esp32/blob/master/src/rtos/rtos_freertos_stackings.c#L371-L374

Maybe you can change conditional above that so the warning is suppressed on your system as well.
