### ISSUE TITLE
[TW#24765] GDB segfault

### ISSUE THREAD

**Issue by michprev** [espressif/openocd-esp32#44]
GDB crashes on my machine: 
Linux acer 4.9.0-6-amd64 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux

I am using b2ff235b ESP-IDF revision, ESP-WROVER-KIT V3.
Example app: https://github.com/michprev/flyhero-esp32/tree/issue_coredump/The_Eye

.gdbinit
```
target remote :3333
mon reset halt
flushregs
set  disassemble-next-line on
show disassemble-next-line
```

Steps to reproduce:
```
> b _WindowOverflow4
> b _WindowOverflow8
> c
Target halted. PRO_CPU: PC=0x40080080 (active)    APP_CPU: PC=0x400076E2
[1]    9457 segmentation fault
```

[openocd_log.txt](https://github.com/espressif/openocd-esp32/files/2109378/openocd_log.txt)
[gdb_log.txt](https://github.com/espressif/openocd-esp32/files/2109379/gdb_log.txt)

**Comment by gerekon** [comment]
That was fixed in out toolchain using temporary solution.  Full solution will be implemented later. Now to overome this problem you need to run GDB with defined envvar `ESP_XTENSA_GDB_PRIV_REGS_FIX=1`
