### ISSUE TITLE
[TW#24766] Software breakpoints not implemented

### ISSUE THREAD

**Issue by michprev** [espressif/openocd-esp32#45]
https://github.com/espressif/openocd-esp32/blob/a9ec3301c18cd8a4b6ea04a7db8132eade4cf0cc/src/target/esp32.c#L860-L863

Althought software breakpoints cannot be set in IROM it would be still useful to have them.
https://esp-idf.readthedocs.io/en/latest/api-guides/jtag-debugging/tips-and-quirks.html#what-else-should-i-know-about-breakpoints is outdated.

**Comment by igrr** [comment]
Software breakpoints have been added in https://github.com/espressif/openocd-esp32/commit/df56722406e76f8d017b0b4101c5895376d602f5. IDF Programming Guide yet to be updated.
