### ISSUE TITLE
[TW#24769] Wrong CCOUNT values when debugging

### ISSUE THREAD

**Issue by michprev** [espressif/openocd-esp32#48]
Using v0.10.0-esp32-20180604 release.

Timer 2 interrupt triggers when `CCOUNT = CCOMPARE2`. In timer 2 interrupt handler I copy CCOUNT and CCOMPARE2 register values to _tmp1 and _tmp2 global variables and then in main loop print them. When not debugging _tmp1 (aka CCOUNT) is always greater than _tmp2 (aka CCOMPARE2) - it should be greater.
But when debugging CCOUNT value is smaller then CCOMPARE2.

Source code available: [https://gitlab.com/michprev/esp32-nonos/tree/issues/gdb_ccount](https://gitlab.com/michprev/esp32-nonos/tree/issues/gdb_ccount)
It is needed to set `XTENSA_TOOLCHAIN` variable to compile, for example `export XTENSA_TOOLCHAIN="$HOME/xtensa-esp32-elf"`
Generated `bootloader.elf` file can be passed to to esptool:
```
esptool.py --chip esp32 --no-stub elf2image cmake-build-debug/bootloader.elf
esptool.py --chip esp32 --no-stub image_info cmake-build-debug/bootloader.bin
esptool.py --chip esp32 --no-stub --port /dev/ttyUSB1 write_flash --flash_freq 40m --flash_mode dio 0x1000 cmake-build-debug/bootloader.bin

miniterm.py --exit-char=113 /dev/ttyUSB1 115200
```

`gdbinit` file:
```
target remote :3333
mon reset halt
flushregs
thb bootloader_start
set  disassemble-next-line on
show disassemble-next-line
```

Steps to reproduce:
```
c
b _Timer2Interrupt
c
ni
ni
p $a3 # prints CCOUNT value
ni
ni
ni
p $a3 # prints CCOMPARE2 value
```

Expected behavior:
CCOUNT contains correct values while debugging (in this case it should be greater than CCOMPARE2 value)

**Comment by erhankur** [comment]
Closed due to inactivity.
