### ISSUE TITLE
[TW#25931] Issue with running gdb on ESP32 Wrover Dev Kit

### ISSUE THREAD

**Issue by igrr** [espressif/openocd-esp32#58]
_From @RA5040 on August 25, 2018 17:34_

## Environment

- Development Kit:   ESP32-Wrover-Kit

- esp-idf-v3.0.3

 - openocd-esp32-win32-0.10.0-esp32-20180724

- Development Env:		Command line

- Operating System:	Windows

## Problem Description

It appears that to run gdb on the ESP32 DevKit C, it's necessary to do things in this order:

1. Make and flash the program
2. Run OpenOCD
3. Run xtensa-esp32-elf-gdb

If OpenOCD is running before flashing the program nothing works.

The Espressif documentation says that OpenOCD should be running, then the program should be flashed, then gdb should be run: https://esp-idf.readthedocs.io/en/latest/api-guides/jtag-debugging/using-debugger.html#jtag-debugging-using-debugger-command-line

So there's either a bug in the code or a bug in the documentation

### Expected Behavior

OpenOCD should be running before flashing and starting gdb

### Actual Behavior

If OpenOCD is running the gdb fails

### Steps to reproduce

Using a ESP32WroverKit with built-in JTAG, follow the Espressif instructions to debug with JTAG in Windows to the letter, build and flash one of the IDF examples (for example blink), and you should see that dbg does not work.

Flash the program, then run OpenOCD, then run the xtensa gdb and hardware debugging should work.

Here is the gdb log:
===============
GNU gdb (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a5) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law. Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=i686-host_pc-mingw32 --target=xtensa-esp32-elf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from build/blink.elf...done.
0x400d1ffa in app_main () at C:/msys32/home/Robert/esp/blink/main/blink.c:45
45 vTaskDelay(1000);
JTAG tap: esp32.cpu0 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
JTAG tap: esp32.cpu1 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
cpu0: Current bits set: BreakIn BreakOut RunStallIn
cpu1: Current bits set: BreakIn BreakOut RunStallIn
esp32: Debug controller was reset (pwrstat=0x5F, after clear 0x0F).
esp32: Core was reset (pwrstat=0x5F, after clear 0x0F).
Target halted. PRO_CPU: PC=0x5000004B (active) APP_CPU: PC=0x00000000
esp32: Core was reset (pwrstat=0x1F, after clear 0x0F).
Target halted. PRO_CPU: PC=0x40000400 (active) APP_CPU: PC=0x40000400
Hardware assisted breakpoint 1 at 0x400d1fdb: file C:/msys32/home/Robert/esp/blink/main/blink.c, line 43.
Target halted. PRO_CPU: PC=0x400D1FDB (active) APP_CPU: PC=0x400D1816
[New Thread 1073435384]
[New Thread 1073433996]
[New Thread 1073438040]
[New Thread 1073426884]
[New Thread 1073412716]
[New Thread 1073413484]
[New Thread 1073428016]
[Switching to Thread 1073432476]

Temporary breakpoint 1, app_main ()
at C:/msys32/home/Robert/esp/blink/main/blink.c:43
43 xTaskCreate(&blink_task, "blink_task", configMINIMAL_STACK_SIZE, NULL, 5, NULL); 
(gdb)

(note that it says temporary breakpoint at app_main (as per the 'thb app_main' parameter)
----> Now some gdb commands
(gdb) n
Note: automatically using hardware breakpoints for read-only addresses.
Target halted. PRO_CPU: PC=0x400D1FF4 (active) APP_CPU: PC=0x40080340
[New Thread 1073439548]
45 vTaskDelay(1000);
(gdb)

2nd N
(gdb) n
... nothing for quite a while then every 5 seconds or so one of these lines is printed:
Target halted. PRO_CPU: PC=0x400D1FFA (active) APP_CPU: PC=0x400D1816
Target halted. PRO_CPU: PC=0x400D1FFA (active) APP_CPU: PC=0x400D1816
Target halted. PRO_CPU: PC=0x400D1FFA (active) APP_CPU: PC=0x400D1816
Target halted. PRO_CPU: PC=0x400D1FFA (active) APP_CPU: PC=0x400D1816
Target halted. PRO_CPU: PC=0x400D1FFA (active) APP_CPU: PC=0x400D1816
Target halted. PRO_CPU: PC=0x400D1FFA (active) APP_CPU: PC=0x400D1816
Target halted. PRO_CPU: PC=0x400D1FFA (active) APP_CPU: PC=0x400D1816
Target halted. PRO_CPU: PC=0x400D1FFA (active) APP_CPU: PC=0x400D1816
Target halted. PRO_CPU: PC=0x400D1FFA (active) APP_CPU: PC=0x400D1816
=======================

and here is the OpenOCD log:
--------------------------------
Open On-Chip Debugger 0.10.0-dev (2018-07-24-09:39)
Licensed under GNU GPL v2
For bug reports, read
http://openocd.org/doc/doxygen/bugs.html
none separate
adapter speed: 20000 kHz
esp32 interrupt mask on
Info : ftdi: if you experience problems at higher adapter clocks, try the command "ftdi_tdo_sample_edge falling"
Info : clock speed 20000 kHz
Info : JTAG tap: esp32.cpu0 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : JTAG tap: esp32.cpu1 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
cpu0: Current bits set: BreakIn BreakOut RunStallIn
cpu1: Current bits set: BreakIn BreakOut RunStallIn

>>>> now run app

Info : accepting 'gdb' connection on tcp/3333
Info : Target halted. PRO_CPU: PC=0x4009170E (active) APP_CPU: PC=0x400D1816
Info : Flash mapping 0: 0x10020 -> 0x3f400020, 23 KB
Info : Flash mapping 1: 0x20018 -> 0x400d0018, 77 KB
Info : Target halted. PRO_CPU: PC=0x4009170E (active) APP_CPU: PC=0x400D1816
Info : Auto-detected flash size 4096 KB
Info : Using flash size 4096 KB
Info : Target halted. PRO_CPU: PC=0x4009170E (active) APP_CPU: PC=0x400D1816
Info : Flash mapping 0: 0x10020 -> 0x3f400020, 23 KB
Info : Flash mapping 1: 0x20018 -> 0x400d0018, 77 KB
Info : Using flash size 80 KB
Info : Target halted. PRO_CPU: PC=0x4009170E (active) APP_CPU: PC=0x400D1816
Info : Flash mapping 0: 0x10020 -> 0x3f400020, 23 KB
Info : Flash mapping 1: 0x20018 -> 0x400d0018, 77 KB
Info : Using flash size 24 KB
Info : JTAG tap: esp32.cpu0 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : JTAG tap: esp32.cpu1 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
cpu0: Current bits set: BreakIn BreakOut RunStallIn
cpu1: Current bits set: BreakIn BreakOut RunStallIn
Info : esp32: Debug controller was reset (pwrstat=0x5F, after clear 0x0F).
Info : esp32: Core was reset (pwrstat=0x5F, after clear 0x0F).
Info : Target halted. PRO_CPU: PC=0x5000004B (active) APP_CPU: PC=0x00000000
Info : esp32: Core was reset (pwrstat=0x1F, after clear 0x0F).
Info : Target halted. PRO_CPU: PC=0x40000400 (active) APP_CPU: PC=0x40000400
Info : Target halted. PRO_CPU: PC=0x400D1FDB (active) APP_CPU: PC=0x400D1816

----> After pressing 'N first time:
Info : Target halted. PRO_CPU: PC=0x400D1FF4 (active) APP_CPU: PC=0x40080340

----> After pressing 'N' 2nd time:
nothing for quite a long time then every 5 seconds or so a line is printed:
Info : Target halted. PRO_CPU: PC=0x400D1FFA (active) APP_CPU: PC=0x400D1816
Info : Target halted. PRO_CPU: PC=0x400D1FFA (active) APP_CPU: PC=0x400D1816
Info : Target halted. PRO_CPU: PC=0x400D1FFA (active) APP_CPU: PC=0x400D1816
Info : Target halted. PRO_CPU: PC=0x400D1FFA (active) APP_CPU: PC=0x400D1816
Info : Target halted. PRO_CPU: PC=0x400D1FFA (active) APP_CPU: PC=0x400D1816
Info : Target halted. PRO_CPU: PC=0x400D1FFA (active) APP_CPU: PC=0x400D1816
Info : Target halted. PRO_CPU: PC=0x400D1FFA (active) APP_CPU: PC=0x400D1816

--------------------------------

and here is the Blink code:
********************************
1	/* Blink Example
2	
3	This example code is in the Public Domain (or CC0 licensed, at your option.)
4	
5	Unless required by applicable law or agreed to in writing, this
6	software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
7	CONDITIONS OF ANY KIND, either express or implied.
8	*/
9	#include <stdio.h>
10	#include "freertos/FreeRTOS.h"
11	#include "freertos/task.h"
12	#include "driver/gpio.h"
13	#include "sdkconfig.h"
14	
15	/* Can run 'make menuconfig' to choose the GPIO to blink,
16	or you can edit the following line and set a number here.
17	*/
18	#define BLINK_GPIO 2
19	
20	void blink_task(void *pvParameter)
21	{
22	/* Configure the IOMUX register for pad BLINK_GPIO (some pads are
23	muxed to GPIO on reset already, but some default to other
24	functions and need to be switched to GPIO. Consult the
25	Technical Reference for a list of pads and their default
26	functions.)
27	*/
28	gpio_pad_select_gpio(BLINK_GPIO);
29	/* Set the GPIO as a push/pull output */
30	gpio_set_direction(BLINK_GPIO, GPIO_MODE_OUTPUT);
31	while(1) {
32	/* Blink off (output low) */
33	gpio_set_level(BLINK_GPIO, 0);
34	vTaskDelay(1000 / portTICK_PERIOD_MS);
35	/* Blink on (output high) */
36	gpio_set_level(BLINK_GPIO, 1);
37	vTaskDelay(1000 / portTICK_PERIOD_MS);
38	}
39	}
40	
41	void app_main()
42	{
43	xTaskCreate(&blink_task, "blink_task", configMINIMAL_STACK_SIZE, NULL, 5, NULL);
44	while(true){
45	vTaskDelay(1000);
46	}
47	}

## Other items if possible

- [ ] sdkconfig file (attach the sdkconfig file from your project folder)
[sdkconfig.zip](https://github.com/espressif/esp-idf/files/2320892/sdkconfig.zip)

- [ ] elf file in the ``build`` folder (**note this may contain all the code details and symbols of your project.**)

[blink.zip](https://github.com/espressif/esp-idf/files/2320891/blink.zip)

_Copied from original issue: espressif/esp-idf#2332_

**Comment by igrr** [comment]
_From @RA5040 on August 26, 2018 11:12_

I was asked to run this again with -d3 on openocd. I attach the log.
[OpenOCDLog.zip](https://github.com/espressif/esp-idf/files/2321462/OpenOCDLog.zip)

**Comment by gerekon** [comment]
@RA5040 I reproduced you this problem with the latest release. But it seems to be solved in the OpenOCD master branch. I built Windows binary for you using that branch. Could you try it?
[openocd.zip](https://github.com/espressif/openocd-esp32/files/2382829/openocd.zip)

**Comment by RA5040** [comment]
I gave it a go, but it is missing libusb-1.0.dll
I tried it again on ubuntu, openocd 0.10.0-dev (2018-07-24-09:36), but it gave the same issue.  If you let me have the executable I'll test it (I don't know how to build it).

**Comment by gerekon** [comment]
@RA5040 Sorry for inconvenience. Could you try this distro. It is build by our release system and should have no problems.
[openocd-esp32-win32-0.10.0-esp32-20180724-2-g59d39ac2.zip](https://github.com/espressif/openocd-esp32/files/2391132/openocd-esp32-win32-0.10.0-esp32-20180724-2-g59d39ac2.zip)

**Comment by kangks** [comment]
Hi,

Not sure if my issue is related to this, I was following the steps in https://github.com/espressif/esp-idf/blob/master/docs/en/api-guides/jtag-debugging/using-debugger.rst

After running `xtensa-esp32-elf-gdb -x gdbinit build/blink.elf`, the LCD stops blinking for a while, but resume blinking after the last line:

```
JTAG tap: esp32.cpu0 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
JTAG tap: esp32.cpu1 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
cpu0: Current bits set: BreakIn BreakOut RunStallIn
cpu1: Current bits set: BreakIn BreakOut RunStallIn
esp32: Debug controller was reset (pwrstat=0x5F, after clear 0x0F).
esp32: Core was reset (pwrstat=0x5F, after clear 0x0F).
Target halted. PRO_CPU: PC=0x5000004B (active)    APP_CPU: PC=0x00000000 
esp32: Core was reset (pwrstat=0x1F, after clear 0x0F).
Target halted. PRO_CPU: PC=0x40000400 (active)    APP_CPU: PC=0x40000400 
Hardware assisted breakpoint 1 at 0x400d1fdb: file /Users/kangrich/Documents/tools/esp-idf-v3.0.5/examples/get-started/blink/main/./blink.c, line 43.
```

gdb and openocd as below, on MAC High Sierrra:

```
$ xtensa-esp32-elf-gdb --version
GNU gdb (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

$ bin/openocd -v
Open On-Chip Debugger 0.10.0-dev (2018-09-20-12:54)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
```

**Comment by kangks** [comment]
Built from the openocd works:

```
GNU gdb (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=x86_64-build_apple-darwin16.3.0 --target=xtensa-esp32-elf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from build/blink.elf...done.
0x400d1afe in esp_vApplicationIdleHook () at /Users/kangrich/Documents/tools/esp-idf-v3.0.5/components/esp32/./freertos_hooks.c:62
62	    asm("waiti 0");
JTAG tap: esp32.cpu0 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
JTAG tap: esp32.cpu1 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
cpu0: Current bits set: BreakIn BreakOut RunStallIn
cpu1: Current bits set: BreakIn BreakOut RunStallIn
esp32: Debug controller was reset (pwrstat=0x5F, after clear 0x0F).
esp32: Core was reset (pwrstat=0x5F, after clear 0x0F).
Target halted. PRO_CPU: PC=0x5000004B (active)    APP_CPU: PC=0x00000000 
esp32: Core was reset (pwrstat=0x1F, after clear 0x0F).
Target halted. PRO_CPU: PC=0x40000400 (active)    APP_CPU: PC=0x40000400 
Hardware assisted breakpoint 1 at 0x400d1fdb: file /Users/kangrich/Documents/tools/esp-idf-v3.0.5/examples/get-started/blink/main/./blink.c, line 43.
Target halted. PRO_CPU: PC=0x400D1FDB (active)    APP_CPU: PC=0x400D1AFE 
[New Thread 1073435424]
[New Thread 1073434036]
[New Thread 1073438080]
[New Thread 1073426924]
[New Thread 1073412716]
[New Thread 1073413484]
[New Thread 1073428056]
[Switching to Thread 1073432516]

Temporary breakpoint 1, app_main () at /Users/kangrich/Documents/tools/esp-idf-v3.0.5/examples/get-started/blink/main/./blink.c:43
43	    xTaskCreate(&blink_task, "blink_task", configMINIMAL_STACK_SIZE, NULL, 5, NULL);
(gdb) i threads
  Id   Target Id         Frame 
  8    Thread 1073428056 (dport) xTaskCreate (pvCreatedTask=0x0, uxPriority=5, pvParameters=0x0, usStackDepth=768, pcName=0x3f402ba8 "blink_task", 
    pvTaskCode=0x400d1fa8 <blink_task>) at /Users/kangrich/Documents/tools/esp-idf-v3.0.5/components/freertos/include/freertos/task.h:427
  7    Thread 1073413484 (ipc0) xTaskCreate (pvCreatedTask=0x0, uxPriority=5, pvParameters=0x0, usStackDepth=768, pcName=0x3f402ba8 "blink_task", 
    pvTaskCode=0x400d1fa8 <blink_task>) at /Users/kangrich/Documents/tools/esp-idf-v3.0.5/components/freertos/include/freertos/task.h:427
  6    Thread 1073412716 (esp_timer) xTaskCreate (pvCreatedTask=0x0, uxPriority=5, pvParameters=0x0, usStackDepth=768, pcName=0x3f402ba8 "blink_task", 
    pvTaskCode=0x400d1fa8 <blink_task>) at /Users/kangrich/Documents/tools/esp-idf-v3.0.5/components/freertos/include/freertos/task.h:427
  5    Thread 1073426924 (ipc1) xTaskCreate (pvCreatedTask=0x0, uxPriority=5, pvParameters=0x0, usStackDepth=768, pcName=0x3f402ba8 "blink_task", 
    pvTaskCode=0x400d1fa8 <blink_task>) at /Users/kangrich/Documents/tools/esp-idf-v3.0.5/components/freertos/include/freertos/task.h:427
  4    Thread 1073438080 (Tmr Svc) xTaskCreate (pvCreatedTask=0x0, uxPriority=5, pvParameters=0x0, usStackDepth=768, pcName=0x3f402ba8 "blink_task", 
    pvTaskCode=0x400d1fa8 <blink_task>) at /Users/kangrich/Documents/tools/esp-idf-v3.0.5/components/freertos/include/freertos/task.h:427
  3    Thread 1073434036 (IDLE) xTaskCreate (pvCreatedTask=0x0, uxPriority=5, pvParameters=0x0, usStackDepth=768, pcName=0x3f402ba8 "blink_task", 
    pvTaskCode=0x400d1fa8 <blink_task>) at /Users/kangrich/Documents/tools/esp-idf-v3.0.5/components/freertos/include/freertos/task.h:427
  2    Thread 1073435424 (IDLE : Running @CPU1) 0x400d1afe in esp_vApplicationIdleHook ()
    at /Users/kangrich/Documents/tools/esp-idf-v3.0.5/components/esp32/./freertos_hooks.c:62
* 1    Thread 1073432516 (main : Running @CPU0) app_main ()
    at /Users/kangrich/Documents/tools/esp-idf-v3.0.5/examples/get-started/blink/main/./blink.c:43
```

**Comment by igrr** [comment]
@RA5040 @kangks New release has been published at https://github.com/espressif/openocd-esp32/releases/, could you please give it a try?

**Comment by zhivko** [comment]
I have similar issue:
```
c:\msys32\home\klemen\esp\openocd-esp32>.\bin\openocd.exe -v
Open On-Chip Debugger 0.10.0-dev (2018-11-05-04:10)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html

c:\msys32\home\klemen\esp\openocd-esp32>.\bin\openocd -s share/openocd/scripts -f interface/ftdi/esp32_devkitj_v1.cfg -f board/esp-wroom-32.cfg
Open On-Chip Debugger 0.10.0-dev (2018-11-05-04:10)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
none separate
adapter speed: 20000 kHz
esp32 interrupt mask on
Error: libusb_open() failed with LIBUSB_ERROR_NOT_SUPPORTED
Info : ftdi: if you experience problems at higher adapter clocks, try the command "ftdi_tdo_sample_edge falling"
Info : clock speed 20000 kHz
Error: JTAG scan chain interrogation failed: all ones
Error: Check JTAG interface, timings, target power, etc.
Error: Trying to use configured scan chain anyway...
Error: esp32.cpu0: IR capture error; saw 0x1f not 0x01
Warn : Bypassing JTAG setup events due to errors
Info : Restore debug stubs @ 0 on core0 of target 'esp32'

c:\msys32\home\klemen\esp\openocd-esp32>.\bin\openocd -s share/openocd/scripts -f interface/ftdi/esp32_devkitj_v1.cfg -f board/esp-wroom-32.cfg
Open On-Chip Debugger 0.10.0-dev (2018-11-05-04:10)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
none separate
adapter speed: 20000 kHz
esp32 interrupt mask on
Error: libusb_open() failed with LIBUSB_ERROR_NOT_SUPPORTED
Info : ftdi: if you experience problems at higher adapter clocks, try the command "ftdi_tdo_sample_edge falling"
Info : clock speed 20000 kHz
Info : JTAG tap: esp32.cpu0 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : JTAG tap: esp32.cpu1 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : esp32: Debug controller 0 was reset (pwrstat=0x5F, after clear 0x0F).
Info : esp32: Core 0 was reset (pwrstat=0x5F, after clear 0x0F).
Info : esp32: Debug controller 0 was reset (pwrstat=0x5F, after clear 0x0F).
Info : esp32: Core 0 was reset (pwrstat=0x5F, after clear 0x0F).
Info : esp32: Debug controller 1 was reset (pwrstat=0x5F, after clear 0x0F).
Info : esp32: Core 1 was reset (pwrstat=0x5F, after clear 0x0F).
Info : Detected debug stubs @ 3ffb3b50 on core0 of target 'esp32'
Info : xtensa_poll: Target offline
Polling target esp32 failed, trying to reexamine
Examination failed, GDB will be halted. Polling again in 100ms
Polling target esp32 failed, trying to reexamine
Examination failed, GDB will be halted. Polling again in 300ms
Polling target esp32 failed, trying to reexamine
Examination failed, GDB will be halted. Polling again in 700ms
Polling target esp32 failed, trying to reexamine
Examination failed, GDB will be halted. Polling again in 1500ms
Polling target esp32 failed, trying to reexamine
Examination failed, GDB will be halted. Polling again in 3100ms
Polling target esp32 failed, trying to reexamine
Examination failed, GDB will be halted. Polling again in 6300ms
Info : accepting 'gdb' connection on tcp/3333


Error: Target not halted
Error: auto_probe failed
Error: Connect failed. Consider setting up a gdb-attach event for the target to prepare target for GDB connect, or use 'gdb_memory_map disable'.
Error: attempted 'gdb' connection rejected
Polling target esp32 failed, trying to reexamine
Examination failed, GDB will be halted. Polling again in 6300ms
```

**Comment by gerekon** [comment]
@zhivko It seems to be another issue. Could you open separate topic for it to keep threads a bit organized? Also please provide full info regarding your problem as it us done in the beginning of this thread.

**Comment by zhivko** [comment]
@gerekon created https://github.com/espressif/openocd-esp32/issues/64

**Comment by igrr** [comment]
@RA5040 @kangks Closing this issue as new release has been published, please feel free to reopen if the issue persists.
