### ISSUE TITLE
Failed to initialize flash in esp32.cfg 

### ISSUE THREAD

**Issue by meriororen** [espressif/openocd-esp32#63]
Hi, I am trying to enable JTAG debugging on my custom board with ESP-WROOM-32 via SEGGER JLINK as interface. With **esp32_dc.cfg**, jtag debugging can be done. Then I realized that in that config file it does not have _program_esp32_ command for flashing the firmwaare, the command is in **esp32.cfg**. However, when I tried to connect gdb to it, it froze after reading symbols (it tries to connect but failed). 

When I comment out the **configure_esp32_flash_bank $_TARGETNAME**, I can debug it, but obviously, I cannot flash it.

Is there a workaround to this? is it possible that there is a bug in determining correct flash size? 

```
Open On-Chip Debugger 0.10.0-dev-00001-g891f429 (2018-10-30-07:41)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
adapter speed: 400 kHz
esp32 interrupt mask on
Info : No device selected, using first device.
Info : J-Link V10 compiled Sep  4 2018 11:24:21
Info : Hardware version: 10.10
Info : VTarget = 3.328 V
Info : clock speed 400 kHz
Info : JTAG tap: esp32.cpu0 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : JTAG tap: esp32.cpu1 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : Target halted. PRO_CPU: PC=0x40090630 (active)    APP_CPU: PC=0x400076E2 
cpu0: Current bits set: BreakIn BreakOut RunStallIn
cpu1: Current bits set: BreakIn BreakOut RunStallIn
Info : accepting 'gdb' connection on tcp/3333
Error: timed out while waiting for target halted / 4 - 2
Info : Target halted. PRO_CPU: PC=0x40090624 (active)    APP_CPU: PC=0x400076E2 
Error: xtensa_wait_algorithm: not halted 0, pc 0x40090624, ps 0x60025
Error: Faied to wait algorithm (-302)!
Error: Algorithm run faied (-302)!
Error: Faied to run flasher stub (-302)!
Warn : Failed to get flash mappings (-302)!
Error: Target is already running an algorithm
Error: Faied to start algorithm (-4)!
Error: Algorithm run faied (-4)!
Error: Faied to run flasher stub (-4)!
Error: Failed to probe flash, size 0 KB
Error: auto_probe failed
Error: Connect failed. Consider setting up a gdb-attach event for the target to prepare target for GDB connect, or use 'gdb_memory_map disable'.
Error: attempted 'gdb' connection rejected

```

Here is the GDB output 

```
GNU gdb (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=x86_64-build_pc-linux-gnu --target=xtensa-esp32-elf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from build/esp32bleprinter.elf...done.
Ignoring packet error, continuing...
warning: unrecognized item "timeout" in "qSupported" response
Ignoring packet error, continuing...
Ignoring packet error, continuing...
gdbinit:1: Error in sourced command file:
Bogus trace status reply from target: timeout
(gdb)  

```
My gdbinit only contains "target remote :3333" if that is relevant.

**Comment by gerekon** [comment]
@meriororen Could you provide the command line you use to run openocd?
Also version of openocd you use (`Open On-Chip Debugger 0.10.0-dev-00001-g891f429 (2018-10-30-07:41)`) looks strange. There is no such release [here](https://github.com/espressif/openocd-esp32/releases). You can get the latest version there. Could you try it?

**Comment by meriororen** [comment]
Hi, Thanks for replying.

I have pulled the latest release's tag (latest commit: 735610e) and built it myself with _./bootstrap_ and _./configure --enable-jlink_ . And then _make_ and _make install_.

I tried using _esp-wroom-32.cfg_ file (and also sourcing jlink interface's jlink.cfg). 
I tried with slower 10000 kHz speed (at 20000 kHz it failed polling). 

and yet it still has the same error (error running flasher stub/ error running algorithm).

```
root@7ef977353931:~/esp32work/esp32bleprinter/psp# openocd -f esp-wroom-32.cfg 
Open On-Chip Debugger 0.10.0-dev (2018-11-07-09:58)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
adapter speed: 10000 kHz
esp32 interrupt mask on
Info : No device selected, using first device.
Info : J-Link V10 compiled Sep  4 2018 11:24:21
Info : Hardware version: 10.10
Info : VTarget = 3.341 V
Info : clock speed 10000 kHz
Info : JTAG tap: esp32.cpu0 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : JTAG tap: esp32.cpu1 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : Target halted. PRO_CPU: PC=0x40090630 (active)    APP_CPU: PC=0x00000000 
Info : accepting 'gdb' connection on tcp/3333
Error: timed out while waiting for target halted / 4 - 2
Info : Target halted. PRO_CPU: PC=0x40090630 (active)    APP_CPU: PC=0x00000000 
Error: xtensa_wait_algorithm: not halted 0, pc 0x40090630, ps 0x60025
Error: Failed to wait algorithm (-302)!
Error: Algorithm run failed (-302)!
Error: Failed to run flasher stub (-302)!
Warn : Failed to get flash mappings (-302)!
Info : Using flash size 0 KB
Error: Target is already running an algorithm
Error: Failed to start algorithm (-4)!
Error: Algorithm run failed (-4)!
Error: Failed to run flasher stub (-4)!
Warn : Failed to get flash mappings (-4)!
Info : Using flash size 0 KB
Info : dropped 'gdb' connection
```
I am thinking of just inserting the flash size parameters in "flash bank" command if that will make any difference.  For typical esp-wroom-32 without spi-flash,  what should the values be?

**Comment by igrr** [comment]
Can you try flashing an example like "blink" to the module first (using `make flash`), just to make sure that this doesn't depend on the firmware?

**Comment by meriororen** [comment]
Actually, I haven't even succeeded in connecting the gdb to the openocd yet. 
So I think the possibility of dependence on firmware is unlikely.

This is me trying to connect without elf file as argument.

> root@7ef977353931:~/esp32work/esp32bleprinter/psp# xtensa-esp32-elf-gdb 
> GNU gdb (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a) 7.10
> Copyright (C) 2015 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
> and "show warranty" for details.
> This GDB was configured as "--host=x86_64-build_pc-linux-gnu --target=xtensa-esp32-elf".
> Type "show configuration" for configuration details.
> For bug reporting instructions, please see:
> <http://www.gnu.org/software/gdb/bugs/>.
> Find the GDB manual and other documentation resources online at:
> <http://www.gnu.org/software/gdb/documentation/>.
> For help, type "help".
> Type "apropos word" to search for commands related to "word".
> (gdb) target remote :3333
> Remote debugging using :3333
> Ignoring packet error, continuing...
> warning: unrecognized item "timeout" in "qSupported" response
> Ignoring packet error, continuing...
> Ignoring packet error, continuing...
> Bogus trace status reply from target: timeout
> (gdb) 
>

**Comment by meriororen** [comment]
> Can you try flashing an example like "blink" to the module first (using `make flash`), just to make sure that this doesn't depend on the firmware?

ah sorry, you mean "make flash". I have no problem flashing it via serial at all.

**Comment by meriororen** [comment]
@gerekon 

1. JTAG adapter type:  **JLink Base** 
2. Release of ESP-IDF used to compile and load application that is being debugged. 
** release tag : v0.10.0-esp32-20181105 (esp-idf commit tag: 735610eeeba122bbaab0879de8b4a44ba0eb928d ) **
** No particular application is being debugged. It fails at the point of connecting via gdb.**
3. Details of OS used for debugging.
uname -a result :
> Linux isa-Latitude-3480 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
lsb_release -a result :
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 16.04.4 LTS
> Release:	16.04
> Codename:	xenial
4. Is OS running natively on a PC or on a virtual machine?
**Native**

openocd execution log :

> isa@isa-Latitude-3480:~/openocd-esp32$ openocd -l openocd_log.txt -d3 -f tcl/interface/jlink.cfg -f tcl/board/esp-wroom-32.cfg -c 'adapter_khz 10000'
> Open On-Chip Debugger 0.10.0-dev (2018-11-08-10:10)
> Licensed under GNU GPL v2
> For bug reports, read
> 	http://openocd.org/doc/doxygen/bugs.html
> 

gdb execution log:

> isa@isa-Latitude-3480:~/openocd-esp32$ xtensa-esp32-elf-gdb 
> GNU gdb (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a) 7.10
> Copyright (C) 2015 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
> and "show warranty" for details.
> This GDB was configured as "--host=x86_64-build_pc-linux-gnu --target=xtensa-esp32-elf".
> Type "show configuration" for configuration details.
> For bug reporting instructions, please see:
> <http://www.gnu.org/software/gdb/bugs/>.
> Find the GDB manual and other documentation resources online at:
> <http://www.gnu.org/software/gdb/documentation/>.
> For help, type "help".
> Type "apropos word" to search for commands related to "word".
> (gdb) set remotelogfile gdb_log.txt
> (gdb) target remote :3333
> Remote debugging using :3333
> Ignoring packet error, continuing...
> warning: unrecognized item "timeout" in "qSupported" response
> Ignoring packet error, continuing...
> Ignoring packet error, continuing...
> Bogus trace status reply from target: timeout
> (gdb) 
> 
> 

other logs :

[openocd_log.txt](https://github.com/espressif/openocd-esp32/files/2560187/openocd_log.txt)
[gdb_log.txt](https://github.com/espressif/openocd-esp32/files/2560188/gdb_log.txt)

**Comment by meriororen** [comment]
Hi, I think I've found the problem. It was as @igrr said, the problem was in the currently running firmware somehow hindering jtag to init flash
