### ISSUE TITLE
debugging ESP-IDF-Template

### ISSUE THREAD

**Issue by pavelskirko** [espressif/openocd-esp32#68]
Hi. I'm trying to program esp32-wroom with  ESP-IDF-Template + led blinking feature and I stuck with a problem. Here is the details:
1. I'm using jlink adapter, the latest stable esp-idf, w10.
2. Here is the code I'm trying to load:
```
esp_err_t event_handler(void *ctx, system_event_t *event)
{
    return ESP_OK;
}

void app_main(void)
{
    gpio_set_direction(27, GPIO_MODE_OUTPUT);
    int level = 0;
    while (1) {
        gpio_set_level(27, level);
        level = !level;
        vTaskDelay(300 / portTICK_PERIOD_MS);
    }
}
```
After successful programming it crashes to panic [openocd_log.txt](https://github.com/espressif/openocd-esp32/files/2797503/openocd_log.txt)
:
```
Program received signal SIGTRAP, Trace/breakpoint trap.
invoke_abort () at C:/msys32/home/Pavel/esp/esp-idf/components/esp32/panic.c:138
138	            __asm__ ("break 0,0");
```
I recorded logs from gdb too:
[gdb_log.txt](https://github.com/espressif/openocd-esp32/files/2797530/gdb_log.txt)
Any ideas?

**Comment by igrr** [comment]
When the program crashes, what is the output on UART console? Also, what is the backtrace from abort() function (you can check using `bt` command in gdb).

**Comment by pavelskirko** [comment]
Unfortunately, I have no UART output in my board(a custom one), there is only JTAG. Here is what I get from backtrace: 
```
(gdb) bt
#0  invoke_abort ()
    at C:/msys32/home/Pavel/esp/esp-idf/components/esp32/panic.c:138
#1  0x4008765e in abort ()
    at C:/msys32/home/Pavel/esp/esp-idf/components/esp32/panic.c:149
#2  0x400d209e in __assert_func (
    file=0x3f402ee8 "C:/msys32/home/Pavel/esp/esp-idf/components/esp32/clk.c", line=69, func=<optimized out>,
    failedexpr=0x3f402eb8 "rtc_clk_xtal_freq_get() != RTC_XTAL_FREQ_AUTO")
    at ../../../.././newlib/libc/stdlib/assert.c:63
#3  0x400d19e9 in esp_clk_init ()
    at C:/msys32/home/Pavel/esp/esp-idf/components/esp32/clk.c:69
#4  0x40080e05 in start_cpu0_default ()
    at C:/msys32/home/Pavel/esp/esp-idf/components/esp32/cpu_start.c:300
#5  0x400810d6 in call_start_cpu0 ()
    at C:/msys32/home/Pavel/esp/esp-idf/components/esp32/cpu_start.c:219
```

**Comment by igrr** [comment]
Please make sure you have flashed bootloader.bin to 0x1000 and partition table binary to 0x8000. It seems that the module was previously flashed (in factory) witb firmware built with old (pre 2.1) version of IDF, and its bootloader is incompatibile with the app you have uploaded.

**Comment by pavelskirko** [comment]
Thank you, It works for me. Problem solved.
