### ISSUE TITLE
Debugging with ESP32-DevKitC v4 not working, not able to halt target (OCD-159)

### ISSUE THREAD

**Issue by VivekRajpara** [espressif/openocd-esp32#69]
Hello,

Greetings!!

Configurations of setup: 
-------------------------------
I am trying to debug blink example program with JLINK JTAG Adapter, this module information is available at [this link](https://www.segger.com/products/debug-probes/j-link/models/j-link-base/)

I have connected ESP32-DevKitC-v4 with JLINK JTAG module by connecting 3v3 (for VRef) TMS, TCK, TDI, TDO & GND pins of ESP32 with respective JLink JTAG interface pins.

I am natively running Linux OS for this debugging purpose.

Release of ESP-IDF -> v3.3-beta1-223-ga62cbfe

Scenario:
-------------
I have flashed board with blink example
Then running blink.elf with gdb after flashing.

Issue:
--------
Target is not halting properly and target still busy errors are reported in openocd and GDB.

Please find attached gdb log, init and openocd logs also.

Can you please help me debug this issue?

[openocd_log.txt](https://github.com/espressif/openocd-esp32/files/2825599/openocd_log.txt)
[gdb_log.txt](https://github.com/espressif/openocd-esp32/files/2825600/gdb_log.txt)
[gdbinit.txt](https://github.com/espressif/openocd-esp32/files/2825608/gdbinit.txt)

**Comment by gerekon** [comment]
@VivekRajpara If it is still actual. Could you check if problem still exists with the latest OpenOCD release (https://github.com/espressif/openocd-esp32/releases/tag/v0.10.0-esp32-20201202)?
