### ISSUE TITLE
Eclipse + openocd-esp32: erratic memory modification, empty Variables tab  (OCD-143)

### ISSUE THREAD

**Issue by JayNaire** [espressif/openocd-esp32#77]
I am using:
- Linux Mint 18
- eclipse 2019-03
- openocd-esp32 Open On-Chip Debugger v0.10.0-esp32-201903 2019-03-13-09:52)
- GNU gdb (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a) 7.10
- ESP_IDF v4.0-dev-512-g6fd535c 12Apr2019
- Olimex-Arm-Usb-Ocd
- Doit esp32 devkit v1 (ESP32-WROOM-32, no on-board ftdi - hence the Olimex )

No showstoppers here; I just thought someone should know:
Debugging (blink as per [example](https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/jtag-debugging/debugging-examples.html#jtag-debugging-examples-eclipse-05)) is generally very stable. 2 annoyances though:

1. Altering memory is difficult in non-traditional renderings. Clicking in a location does not highlight that location (the whole row is highlighted as below) neither is a text cursor displayed. You can type in a value but the display will not show input until return is hit when the new value may or may not be updated and when an input error message may or may not be displayed.  It  may or may not result in the variable being changed in code.
![Selection_040](https://user-images.githubusercontent.com/1676662/58515783-e1397b00-819d-11e9-9f1c-d6d9e5406daa.png)

In traditional renderings things work much as expected (note the text cursor - input is also correctly echoed as typed):

![Selection_041](https://user-images.githubusercontent.com/1676662/58516464-e992b580-819f-11e9-881c-fd77424d6ba0.png)

2. The Variables tab in the Debugging pane never shows any variables<sup>1</sup>. (this was also the case testing out linux + vscode + gdb + openocd-esp32). (I miss the tree display; it was invaluable when debugging NXP and Atmel processors.)
<sup>1</sup>Note: Dragging variables/expressions to the Expressions tab works well though.

 Any instant remedies gratefully received!

**Comment by gerekon** [comment]
Looks like this issue is related Eclipse IDE. So I am closing it here. If you still have this problem in [IDF Eclipse plugin](https://github.com/espressif/idf-eclipse-plugin), please, report issue there.

**Comment by gerekon** [comment]
Looks like this issue is related Eclipse IDE. So I am closing it here. If you still have this problem in [IDF Eclipse plugin](https://github.com/espressif/idf-eclipse-plugin), please, report issue there.
