### ISSUE TITLE
Flash download over JTAG

### ISSUE THREAD

**Issue by saeugetier** [espressif/openocd-esp32#8]
Hi devs,
are there any plans to enable writing the program to flash over JTAG?
Currently the program has to be  transferred via uart.

**Comment by zhivko** [comment]
That would be really nice feature and it would release serial pins for another things.. so :+1: for this issue and looking forward for resolution.

**Comment by EndlessDelirium** [comment]
I also think that this improvement would be a highly appreciated by many.
Sysprogs VisualGDB already supports this. So maybe the corresponding can be merged back from their OpenOCD fork?
Furthermore there is already an ongoing forum discussion: https://esp32.com/viewtopic.php?f=2&t=854&start=10

**Comment by igrr** [comment]
Fixed in a8595645
