### ISSUE TITLE
Failed make: cast between incompatible function types (OCD-193)

### ISSUE THREAD

**Issue by selaliadobor-wt** [espressif/openocd-esp32#86]
> **src/target/xtensa_algorithm.c:547:22:**
> **warning: cast between incompatible function types**  from ‘**int (*)(struct target *, struct xtensa_algo_run_data *, uint32_t)**’ to ‘**int (*)(struct target *, struct xtensa_algo_run_data *, void *)**’ [-Wcast-function-type]
>                  **_run->algo_func = (xtensa_algo_func_t)xtensa_run_algorithm_onboard;_**

Currently building with `-Wall` and `-Werror` removed as a work around

**Comment by fromeijn** [comment]
Same issue here

**Comment by gerekon** [comment]
@selaliadobor-wt  @fromeijn Could you post GCC version number you use?

**Comment by redmercury** [comment]
I also get this error.  Compiling on Debian 10 (Buster).
gcc --version = gcc (Debian 8.3.0-6) 8.3.0

**Comment by WernerMauss** [comment]
Same issue here. Compiling on Raspbian 10 (Buster). 
gcc --version = gcc (Raspbian 8.3.0-6+rpi1) 8.3.0

**Comment by WernerMauss** [comment]
> Currently building with `-Wall` and `-Werror` removed as a work around

How did you remove them?

**Comment by gerekon** [comment]
Ok, reproduced. Will be fixed soon. Thanks, guys!

**Comment by gerekon** [comment]
Closed with 4ce5744e
