### ISSUE TITLE
py_debug_backend repository doesn't exist

### ISSUE THREAD

**Issue by mbilloo** [espressif/openocd-esp32#94]
When checking out master and running ./bootstrap, checkout of https://github.com/espressif/py_debug_backend.git/ during submodule checkout fails because the repo doesn't exist.

**Comment by XaviDCR92** [comment]
I can confirm this issue as well. I have tried removing the entry from `.gitmodules`:

`
[submodule "testing/esp/py_debug_backend"]
	path = testing/esp/py_debug_backend
	url = ../../espressif/py_debug_backend.git
`
Then I ran `git submodule sync` with no luck. For some reason, `py_debug_backend` is still being referrenced on `.git/index`.

**Comment by mbilloo** [comment]
This will require a PR since the reference to the submodule will need to be removed from the index (https://stackoverflow.com/questions/1260748/how-do-i-remove-a-submodule#1260982).

**Comment by gerekon** [comment]
Yes. We have not published that repo yet. It is used only for running our tests. We will remove that reference soon.
