### ISSUE TITLE
'cmsis_dap_handle_cmd_command' redefined error

### ISSUE THREAD

**Issue by awander** [espressif/openocd-esp32#96]
'cmsis_dap_handle_cmd_command' is redefined at:
src/jtag/drivers/cmsis_dap_usb.c:1664:17: 
and 
src/jtag/drivers/cmsis_dap_usb.c:1688:17:

It's the totally same define!

I remove the second one, it works.

**Comment by gerekon** [comment]
@awander  Could you post steps to reproduce this error?

**Comment by gerekon** [comment]
It seems should be fixed with https://github.com/espressif/openocd-esp32/pull/93

**Comment by gerekon** [comment]
Closed with 554180e6af29e760799ecfe4d50be2dae5af3135
